#!/usr/bin/env python3
"""Generate portable combinational ternary decoders; no vendor LUT assumptions."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LANE_BITS = {-1: 0b10, 0: 0b00, 1: 0b01}


def lanes(trits: list[int]) -> int:
    return sum(LANE_BITS[trit] << (2 * index) for index, trit in enumerate(trits))


def decoder(name: str, width: int, trits: int, entries: list[int]) -> str:
    lines = [
        "// Generated by scripts/generate_rtl.py; do not edit by hand.",
        "// Combinational truth table. FPGA resource mapping requires synthesis.",
        "`timescale 1ns/1ps",
        "`default_nettype none",
        f"module {name} (",
        f"    input wire [{width - 1}:0] code,",
        f"    output reg [{2 * trits - 1}:0] trits,",
        "    output reg valid",
        ");",
        "    always @* begin",
        f"        trits = {2 * trits}'d0;",
        "        valid = 1'b1;",
        "        case (code)",
    ]
    for code, output in enumerate(entries):
        lines.append(f"            {width}'d{code}: trits = {2 * trits}'d{output};")
    lines += [
        "            default: begin",
        f"                trits = {2 * trits}'d0;",
        "                valid = 1'b0;",
        "            end",
        "        endcase",
        "    end",
        "endmodule",
        "`default_nettype wire",
        "",
    ]
    return "\n".join(lines)


def generated_files() -> dict[Path, str]:
    dense = []
    for code in range(3**5):
        value, trits = code, []
        for _ in range(5):
            digit = value % 3
            trits.append(digit - 1)
            value //= 3
        dense.append(lanes(trits))
    sparse = [0]
    for position in range(4):
        for sign in (-1, 1):
            trits = [0] * 4
            trits[position] = sign
            sparse.append(lanes(trits))
    return {
        ROOT / "rtl/generated/ternary_dense5_decoder.v": decoder(
            "ternary_dense5_decoder", 8, 5, dense
        ),
        ROOT / "rtl/generated/ternary_sparse41_decoder.v": decoder(
            "ternary_sparse41_decoder", 4, 4, sparse
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()
    different = []
    for path, contents in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text() != contents:
                different.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)
    if different:
        print("Generated RTL differs: " + ", ".join(different))
        return 1
    print("Generated RTL is current." if args.check else "Generated dense5 and sparse41 decoders.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
