"""Copy the TQ1_0/TQ2_0 functions of pinned llama.cpp sources into one C file.

I/O glue for the llama.cpp issue 15193 harness: it copies verbatim line ranges
listed in tests/upstream/llama.cpp.lock.json from the files that
tools/fetch-upstream.sh placed in build/upstream/, and refuses to write
anything when a file's sha256 differs from the lock or a range does not begin
and end with the expected lines. The output is a build product and is never
committed (llama.cpp is MIT-licensed; see the lock).
"""
from __future__ import annotations
import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GUARDS = {"": None, "arm": "defined(__ARM_NEON)", "x86": "defined(__x86_64__)",
          "x86_avx": "defined(__x86_64__) && defined(__AVX2__)"}


def extract(lock_path: Path, output: Path) -> int:
    lock = json.loads(lock_path.read_text())
    base = ROOT / "build" / "upstream" / lock["directory"]
    lines = {}
    for path, meta in lock["files"].items():
        data = (base / path).read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        if digest != meta["sha256"]:
            raise SystemExit(f"{path}: sha256 {digest} differs from the lock {meta['sha256']};"
                             " run sh tools/fetch-upstream.sh")
        lines[path] = data.decode("utf-8").split("\n")
    short = lock["commit"][:8]
    out = [f"/* Generated by tests/upstream/extract_llamacpp_tq.py from {lock['repo']}@{lock['commit']}.",
           f" * Verbatim line ranges; license: {lock['license']}. Do not edit or commit. */",
           '#include "llamacpp_prelude.h"']
    for item in lock["extracts"]:
        path, first, last = item["file"], item["first"], item["last"]
        text = lines[path][first - 1:last]
        if len(text) != last - first + 1:
            raise SystemExit(f"{path}:{first}-{last}: file has only {len(lines[path])} lines")
        if not text[0].startswith(item["first_line"]):
            raise SystemExit(f"{path}:{first}: expected a line starting with {item['first_line']!r}, found {text[0]!r}")
        if not text[-1].startswith(item["last_line"]):
            raise SystemExit(f"{path}:{last}: expected a line starting with {item['last_line']!r}, found {text[-1]!r}")
        guard = GUARDS[item["guard"]]
        out.append(f"/* {path}:{first}-{last} at {short} */")
        if guard:
            out.append(f"#if {guard}")
        out.extend(text)
        if guard:
            out.append("#endif")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out) + "\n")
    print(f"extracted {len(lock['extracts'])} ranges from {lock['repo']}@{short} into {output}")
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--lock", type=Path, default=ROOT / "tests" / "upstream" / "llama.cpp.lock.json")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    return extract(args.lock, args.output)


if __name__ == "__main__":
    sys.exit(main())
