// ============================================================================
// Generated from t27 spec: TrinityGf16AttnT27
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module TrinityGf16AttnT27 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    input  wire calib,
    input  wire stall,
    input  wire ack,
    input  wire [63:0] rdata_lo,
    input  wire [63:0] rdata_hi,
    input  wire [31:0] hidden,
    input  wire [31:0] kv,
    input  wire [31:0] heads,
    input  wire [31:0] kv_heads,
    input  wire [31:0] head_dim,
    input  wire line_idle,
    input  wire s_go,
    input  wire [31:0] s_tag,
    input  wire [31:0] s_a,
    input  wire [63:0] s_b,
    output wire        ready,
    output reg [31:0] state,
    output reg [31:0] index,
    output reg [31:0] row,
    output reg [31:0] col,
    output reg [31:0] bitpos,
    output reg [31:0] head,
    output reg [31:0] pos,
    output reg [31:0] pair,
    output reg [31:0] jj,
    output reg [31:0] dd,
    output reg [31:0] kvcount,
    output reg [31:0] nrows,
    output reg [31:0] ropebase,
    output reg [31:0] group,
    output reg [31:0] pairs,
    output reg [31:0] weight_addr,
    output reg [31:0] last_run,
    output reg [31:0] run_id,
    output reg [31:0] poll,
    output reg active,
    output reg [63:0] cycles,
    output reg [63:0] report_cycles,
    output reg [63:0] memory_cycles,
    output reg result_only,
    output reg [31:0] positions,
    output reg [31:0] error_code,
    output reg [31:0] scale_q,
    output reg [31:0] scale_k,
    output reg [31:0] scale_v,
    output reg [31:0] scale_o,
    output reg [31:0] scale_attn,
    output reg [63:0] lane,
    output reg [63:0] acc0,
    output reg [63:0] acc1,
    output reg [63:0] term0,
    output reg [63:0] term1,
    output reg [63:0] add0,
    output reg [63:0] add1,
    output reg [63:0] add_carry,
    output reg [63:0] weight0,
    output reg [63:0] weight1,
    output reg wb_cyc,
    output reg wb_stb,
    output reg [31:0] wb_addr,
    output reg [31:0] response,
    output reg [63:0] read0,
    output reg [63:0] read1,
    output reg [31:0] quiet,
    output reg pending,
    output reg [31:0] ptag,
    output reg [31:0] pa,
    output reg [63:0] pb,
    output reg [31:0] emit_tag,
    output reg [31:0] emit_value,
    output reg [31:0] emit_index,
    output reg [31:0] after_emit,
    output reg [31:0] arb,
    output reg sbuf,
    output reg [31:0] sb_tag,
    output reg [31:0] sb_a,
    output reg [63:0] sb_b,
    output reg line_go,
    output reg [31:0] line_tag,
    output reg [31:0] line_a,
    output reg [63:0] line_b,
    output reg s_idle,
    output reg [63:0] sumsq0,
    output reg [63:0] sumsq1,
    output reg [63:0] rem0,
    output reg [63:0] rem1,
    output reg [63:0] quo0,
    output reg [63:0] quo1,
    output reg [63:0] divisor,
    output reg [63:0] root,
    output reg [63:0] rms,
    output reg [63:0] sub0,
    output reg [63:0] sub1,
    output reg [63:0] cmp0,
    output reg [63:0] cmp1,
    output reg [63:0] num_mag,
    output reg num_sign,
    output reg [63:0] out_mag,
    output reg [63:0] quant,
    output reg [63:0] twice,
    output reg [63:0] inc,
    output reg [31:0] exp_value,
    output reg [31:0] exp_denom,
    output reg [31:0] norm_pass,
    output reg [31:0] projection_stage,
    output reg [31:0] store_base,
    output reg [31:0] proj_scale,
    output reg [31:0] proj_tag,
    output reg [31:0] sample_q,
    output reg [31:0] weight_q,
    output reg [31:0] cos_q,
    output reg [31:0] sin_q,
    output reg [63:0] term2,
    output reg [63:0] term3,
    output reg [31:0] max_score,
    output reg [31:0] sc_index,
    output reg [63:0] mul_a,
    output reg [63:0] mul_b,
    output reg [63:0] mul_left,
    output reg [63:0] mul_right,
    output reg [63:0] mul_product,
    output reg [31:0] mul_bit,
    output reg [31:0] mul_return,
    output reg [63:0] scale_low_product,
    output reg [63:0] scale_high_carry,
    output reg [63:0] exp_z,
    output reg [31:0] exp_m,
    output reg [31:0] exp_j,
    output reg [63:0] exp_g,
    output reg [63:0] exp_h,
    output reg [63:0] exp_a2,
    output reg [63:0] exp_a1,
    output reg [63:0] exp_a0,
    output reg [63:0] exp_b1,
    output reg [63:0] exp_b0,
    output reg [63:0] exp_p,
    output reg [63:0] exp_y,
    output reg [63:0] rne_num,
    output reg [31:0] rne_bits,
    output reg [31:0] rne_return,
    output reg [63:0] rne_q,
    output reg [63:0] rne_rem,
    output reg [63:0] rne_half,
    output reg div_round_up,
    output reg [31:0] sqrt_shift,
    output reg sqrt_upper,
    output reg rne_up,
    output reg [63:0] rne_result,
    output reg [31:0] va,
    output reg [31:0] ga,
    output reg [31:0] ua,
    output reg [31:0] vr2,
    output reg [31:0] gr2,
    output reg [31:0] ur2
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    // state exposed as output reg port
    initial begin
        state = 0;
    end

    // index exposed as output reg port
    initial begin
        index = 0;
    end

    // row exposed as output reg port
    initial begin
        row = 0;
    end

    // col exposed as output reg port
    initial begin
        col = 0;
    end

    // bitpos exposed as output reg port
    initial begin
        bitpos = 0;
    end

    // head exposed as output reg port
    initial begin
        head = 0;
    end

    // pos exposed as output reg port
    initial begin
        pos = 0;
    end

    // pair exposed as output reg port
    initial begin
        pair = 0;
    end

    // jj exposed as output reg port
    initial begin
        jj = 0;
    end

    // dd exposed as output reg port
    initial begin
        dd = 0;
    end

    // kvcount exposed as output reg port
    initial begin
        kvcount = 0;
    end

    // nrows exposed as output reg port
    initial begin
        nrows = 0;
    end

    // ropebase exposed as output reg port
    initial begin
        ropebase = 0;
    end

    // group exposed as output reg port

    // pairs exposed as output reg port
    initial begin
        pairs = 0;
    end

    // weight_addr exposed as output reg port
    initial begin
        weight_addr = 0;
    end

    // last_run exposed as output reg port
    initial begin
        last_run = 0;
    end

    // run_id exposed as output reg port
    initial begin
        run_id = 0;
    end

    // poll exposed as output reg port
    initial begin
        poll = 0;
    end

    // active exposed as output reg port
    initial begin
        active = 1'b0;
    end

    // cycles exposed as output reg port
    initial begin
        cycles = 0;
    end

    // report_cycles exposed as output reg port
    initial begin
        report_cycles = 0;
    end

    // memory_cycles exposed as output reg port
    initial begin
        memory_cycles = 0;
    end

    // result_only exposed as output reg port
    initial begin
        result_only = 1'b0;
    end

    // positions exposed as output reg port
    initial begin
        positions = 0;
    end

    // error_code exposed as output reg port
    initial begin
        error_code = 0;
    end

        reg [31:0] vec[0:8191];

        reg [31:0] gate[0:8191];

        reg [31:0] up[0:8191];

    // scale_q exposed as output reg port
    initial begin
        scale_q = 0;
    end

    // scale_k exposed as output reg port
    initial begin
        scale_k = 0;
    end

    // scale_v exposed as output reg port
    initial begin
        scale_v = 0;
    end

    // scale_o exposed as output reg port
    initial begin
        scale_o = 0;
    end

    // scale_attn exposed as output reg port
    initial begin
        scale_attn = 0;
    end

    // lane exposed as output reg port
    initial begin
        lane = 0;
    end

    // acc0 exposed as output reg port
    initial begin
        acc0 = 0;
    end

    // acc1 exposed as output reg port
    initial begin
        acc1 = 0;
    end

    // term0 exposed as output reg port
    initial begin
        term0 = 0;
    end

    // term1 exposed as output reg port
    initial begin
        term1 = 0;
    end

    // add0 exposed as output reg port
    initial begin
        add0 = 0;
    end

    // add1 exposed as output reg port
    initial begin
        add1 = 0;
    end

    // add_carry exposed as output reg port
    initial begin
        add_carry = 0;
    end

    // weight0 exposed as output reg port
    initial begin
        weight0 = 0;
    end

    // weight1 exposed as output reg port
    initial begin
        weight1 = 0;
    end

    // wb_cyc exposed as output reg port
    initial begin
        wb_cyc = 1'b0;
    end

    // wb_stb exposed as output reg port
    initial begin
        wb_stb = 1'b0;
    end

    // wb_addr exposed as output reg port
    initial begin
        wb_addr = 0;
    end

    // response exposed as output reg port
    initial begin
        response = 0;
    end

    // read0 exposed as output reg port
    initial begin
        read0 = 0;
    end

    // read1 exposed as output reg port
    initial begin
        read1 = 0;
    end

    // quiet exposed as output reg port
    initial begin
        quiet = 0;
    end

    // pending exposed as output reg port
    initial begin
        pending = 1'b0;
    end

    // ptag exposed as output reg port
    initial begin
        ptag = 0;
    end

    // pa exposed as output reg port
    initial begin
        pa = 0;
    end

    // pb exposed as output reg port
    initial begin
        pb = 0;
    end

    // emit_tag exposed as output reg port
    initial begin
        emit_tag = 0;
    end

    // emit_value exposed as output reg port
    initial begin
        emit_value = 0;
    end

    // emit_index exposed as output reg port
    initial begin
        emit_index = 0;
    end

    // after_emit exposed as output reg port
    initial begin
        after_emit = 0;
    end

    // arb exposed as output reg port
    initial begin
        arb = 0;
    end

    // sbuf exposed as output reg port
    initial begin
        sbuf = 1'b0;
    end

    // sb_tag exposed as output reg port
    initial begin
        sb_tag = 0;
    end

    // sb_a exposed as output reg port
    initial begin
        sb_a = 0;
    end

    // sb_b exposed as output reg port
    initial begin
        sb_b = 0;
    end

    // line_go exposed as output reg port
    initial begin
        line_go = 1'b0;
    end

    // line_tag exposed as output reg port
    initial begin
        line_tag = 0;
    end

    // line_a exposed as output reg port
    initial begin
        line_a = 0;
    end

    // line_b exposed as output reg port
    initial begin
        line_b = 0;
    end

    // s_idle exposed as output reg port

    // sumsq0 exposed as output reg port
    initial begin
        sumsq0 = 0;
    end

    // sumsq1 exposed as output reg port
    initial begin
        sumsq1 = 0;
    end

    // rem0 exposed as output reg port
    initial begin
        rem0 = 0;
    end

    // rem1 exposed as output reg port
    initial begin
        rem1 = 0;
    end

    // quo0 exposed as output reg port
    initial begin
        quo0 = 0;
    end

    // quo1 exposed as output reg port
    initial begin
        quo1 = 0;
    end

    // divisor exposed as output reg port
    initial begin
        divisor = 0;
    end

    // root exposed as output reg port
    initial begin
        root = 0;
    end

    // rms exposed as output reg port
    initial begin
        rms = 0;
    end

    // sub0 exposed as output reg port
    initial begin
        sub0 = 0;
    end

    // sub1 exposed as output reg port
    initial begin
        sub1 = 0;
    end

    // cmp0 exposed as output reg port
    initial begin
        cmp0 = 0;
    end

    // cmp1 exposed as output reg port
    initial begin
        cmp1 = 0;
    end

    // num_mag exposed as output reg port
    initial begin
        num_mag = 0;
    end

    // num_sign exposed as output reg port
    initial begin
        num_sign = 1'b0;
    end

    // out_mag exposed as output reg port
    initial begin
        out_mag = 0;
    end

    // quant exposed as output reg port
    initial begin
        quant = 0;
    end

    // twice exposed as output reg port
    initial begin
        twice = 0;
    end

    // inc exposed as output reg port
    initial begin
        inc = 0;
    end

    // exp_value exposed as output reg port
    initial begin
        exp_value = 0;
    end

    // exp_denom exposed as output reg port
    initial begin
        exp_denom = 0;
    end

    // norm_pass exposed as output reg port
    initial begin
        norm_pass = 0;
    end

    // projection_stage exposed as output reg port
    initial begin
        projection_stage = 0;
    end

    // store_base exposed as output reg port
    initial begin
        store_base = 0;
    end

    // proj_scale exposed as output reg port
    initial begin
        proj_scale = 0;
    end

    // proj_tag exposed as output reg port
    initial begin
        proj_tag = 0;
    end

    // sample_q exposed as output reg port
    initial begin
        sample_q = 0;
    end

    // weight_q exposed as output reg port
    initial begin
        weight_q = 0;
    end

    // cos_q exposed as output reg port
    initial begin
        cos_q = 0;
    end

    // sin_q exposed as output reg port
    initial begin
        sin_q = 0;
    end

    // term2 exposed as output reg port
    initial begin
        term2 = 0;
    end

    // term3 exposed as output reg port
    initial begin
        term3 = 0;
    end

    // max_score exposed as output reg port
    initial begin
        max_score = 0;
    end

    // sc_index exposed as output reg port
    initial begin
        sc_index = 0;
    end

    // mul_a exposed as output reg port
    initial begin
        mul_a = 0;
    end

    // mul_b exposed as output reg port
    initial begin
        mul_b = 0;
    end

    // mul_left exposed as output reg port
    initial begin
        mul_left = 0;
    end

    // mul_right exposed as output reg port
    initial begin
        mul_right = 0;
    end

    // mul_product exposed as output reg port
    initial begin
        mul_product = 0;
    end

    // mul_bit exposed as output reg port
    initial begin
        mul_bit = 0;
    end

    // mul_return exposed as output reg port
    initial begin
        mul_return = 0;
    end

    // scale_low_product exposed as output reg port
    initial begin
        scale_low_product = 0;
    end

    // scale_high_carry exposed as output reg port
    initial begin
        scale_high_carry = 0;
    end

    // exp_z exposed as output reg port
    initial begin
        exp_z = 0;
    end

    // exp_m exposed as output reg port
    initial begin
        exp_m = 0;
    end

    // exp_j exposed as output reg port
    initial begin
        exp_j = 0;
    end

    // exp_g exposed as output reg port
    initial begin
        exp_g = 0;
    end

    // exp_h exposed as output reg port
    initial begin
        exp_h = 0;
    end

    // exp_a2 exposed as output reg port
    initial begin
        exp_a2 = 0;
    end

    // exp_a1 exposed as output reg port
    initial begin
        exp_a1 = 0;
    end

    // exp_a0 exposed as output reg port
    initial begin
        exp_a0 = 0;
    end

    // exp_b1 exposed as output reg port
    initial begin
        exp_b1 = 0;
    end

    // exp_b0 exposed as output reg port
    initial begin
        exp_b0 = 0;
    end

    // exp_p exposed as output reg port
    initial begin
        exp_p = 0;
    end

    // exp_y exposed as output reg port
    initial begin
        exp_y = 0;
    end

    // rne_num exposed as output reg port
    initial begin
        rne_num = 0;
    end

    // rne_bits exposed as output reg port
    initial begin
        rne_bits = 0;
    end

    // rne_return exposed as output reg port
    initial begin
        rne_return = 0;
    end

    // rne_q exposed as output reg port
    initial begin
        rne_q = 0;
    end

    // rne_rem exposed as output reg port
    initial begin
        rne_rem = 0;
    end

    // rne_half exposed as output reg port
    initial begin
        rne_half = 0;
    end

    // div_round_up exposed as output reg port
    initial begin
        div_round_up = 1'b0;
    end

    // sqrt_shift exposed as output reg port
    initial begin
        sqrt_shift = 0;
    end

    // sqrt_upper exposed as output reg port
    initial begin
        sqrt_upper = 1'b0;
    end

    // rne_up exposed as output reg port
    initial begin
        rne_up = 1'b0;
    end

    // rne_result exposed as output reg port
    initial begin
        rne_result = 0;
    end

    // va exposed as output reg port

    // ga exposed as output reg port

    // ua exposed as output reg port

    // vr2 exposed as output reg port
    initial begin
        vr2 = 0;
    end

    // gr2 exposed as output reg port
    initial begin
        gr2 = 0;
    end

    // ur2 exposed as output reg port
    initial begin
        ur2 = 0;
    end


    // -------------------------------------------------------
    // R-SI-1: multiplication helper (no `*` operator)
    // -------------------------------------------------------
    function [63:0] __mul_noop; // t27#1886: 64-bit, u64 products no longer truncate
        input [63:0] a;
        input [63:0] b;
        integer i;
        reg [127:0] acc;
        begin
            acc = 128'd0;
            for (i = 0; i < 64; i = i + 1) begin
                if (b[i]) acc = acc + ({64'd0, a} << i);
            end
            __mul_noop = acc[63:0];
        end
    endfunction

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: pick
    function [63:0] pick; // -> u64
        input flag;
        input [63:0] a;
        input [63:0] b;
        begin : pick_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            if (flag) begin
                pick = a;
                __t27_ret = 1'b1;
            end else begin
                pick = b;
                __t27_ret = 1'b1;
            end
        end
    endfunction

    // function: carry
    function [63:0] carry; // -> u64
        input [63:0] a;
        input [63:0] b;
        begin : carry_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            carry = (((a & b) | ((a | b) & ((a + b) ^ 64'd18446744073709551615))) >>> 63);
            __t27_ret = 1'b1;
        end
    endfunction

    // function: rne_shift
    function [63:0] rne_shift; // -> u64
        input [63:0] num;
        input [31:0] shift;
        begin : rne_shift_body
            reg [63:0] q;
            reg [63:0] rem;
            reg [63:0] half;
            reg __t27_ret;
            __t27_ret = 1'b0;
            q = (num >> shift);
            rem = (num & ((1 << shift) - 1));
            half = (1 << (shift - 1));
            if ((rem > half)) begin
                rne_shift = (q + 1);
                __t27_ret = 1'b1;
            end else begin
                if ((rem == half)) begin
                    if (((q & 1) != 0)) begin
                        rne_shift = (q + 1);
                        __t27_ret = 1'b1;
                    end
                end
                if (!__t27_ret) begin
                    rne_shift = q;
                    __t27_ret = 1'b1;
                end
            end
        end
    endfunction

    // function: exp_q16
    function [31:0] exp_q16; // -> u32
        input [31:0] delta;
        begin : exp_q16_body
            reg [63:0] z;
            reg [63:0] u;
            reg [31:0] m;
            reg [63:0] f;
            reg [31:0] j;
            reg [63:0] g;
            reg [63:0] h;
            reg [1023:0] t;
            reg [63:0] a2;
            reg [63:0] a1;
            reg [63:0] a0;
            reg [63:0] b1;
            reg [63:0] b0;
            reg [63:0] p;
            reg [63:0] y;
            reg __t27_ret;
            __t27_ret = 1'b0;
            z = ((0 - delta) & 64'd4294967295);
            if (($signed({1'b0, z}) >= $signed(772244))) begin
                exp_q16 = 0;
                __t27_ret = 1'b1;
            end else begin
                u = __mul_noop(z, 64'd6196328019);
                m = ((u >> 48) & {32{1'b1}});
                f = (u & 64'd281474976710655);
                j = ((f >> 44) & {32{1'b1}});
                g = ((f & 64'd17592186044415) >>> 16);
                h = (__mul_noop(g, g) >> 32);
                t = {64'd2242560872, 64'd2341847524, 64'd2445529972, 64'd2553802834, 64'd2666869345, 64'd2784941738, 64'd2908241642, 64'd3037000500, 64'd3171459999, 64'd3311872529, 64'd3458501653, 64'd3611622603, 64'd3771522796, 64'd3938502376, 64'd4112874773, 64'd4294967296};
                a2 = ((__mul_noop(661577, h) >>> 32) + 41309550);
                a1 = ((__mul_noop(a2, h) >> 32) + 64'd1031764991);
                a0 = ((__mul_noop(a1, h) >> 32) + 64'd4294967296);
                b1 = ((__mul_noop(5726720, h) >>> 32) + 238388332);
                b0 = ((__mul_noop(b1, h) >> 32) + 64'd2977044472);
                p = (a0 - (__mul_noop(g, b0) >> 32));
                y = pick((j == 0), p, (__mul_noop(t[((j) * 64) +: 64], p) >> 32));
                exp_q16 = (rne_shift(y, (16 + m)) & {32{1'b1}});
                __t27_ret = 1'b1;
            end
        end
    endfunction

    // function: sign64
    function sign64; // -> bool
        input [31:0] word;
        begin : sign64_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            sign64 = ((word >> 31) != 0);
            __t27_ret = 1'b1;
        end
    endfunction

    // function: sgt
    function sgt; // -> bool
        input [63:0] a;
        input [63:0] b;
        begin : sgt_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            if ((((a >> 63) != 0) != ((b >> 63) != 0))) begin
                sgt = ((a >> 63) == 0);
                __t27_ret = 1'b1;
            end else begin
                sgt = (a > b);
                __t27_ret = 1'b1;
            end
        end
    endfunction

    // function: extend
    function [63:0] extend; // -> u64
        input [31:0] word;
        begin : extend_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            if (((word >> 31) != 0)) begin
                extend = (word | 64'd18446744069414584320);
                __t27_ret = 1'b1;
            end else begin
                extend = word;
                __t27_ret = 1'b1;
            end
        end
    endfunction

    // function: mag64
    function [63:0] mag64; // -> u64
        input [31:0] word;
        begin : mag64_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            if (((word >> 31) != 0)) begin
                mag64 = ((0 - word) & 64'd4294967295);
                __t27_ret = 1'b1;
            end else begin
                mag64 = word;
                __t27_ret = 1'b1;
            end
        end
    endfunction

    // function: exp_lut
    function [63:0] exp_lut; // -> u64
        input [31:0] j;
        begin : exp_lut_body
            reg [1023:0] t;
            reg __t27_ret;
            __t27_ret = 1'b0;
            t = {64'd2242560872, 64'd2341847524, 64'd2445529972, 64'd2553802834, 64'd2666869345, 64'd2784941738, 64'd2908241642, 64'd3037000500, 64'd3171459999, 64'd3311872529, 64'd3458501653, 64'd3611622603, 64'd3771522796, 64'd3938502376, 64'd4112874773, 64'd4294967296};
            exp_lut = t[((j) * 64) +: 64];
            __t27_ret = 1'b1;
        end
    endfunction

    // -------------------------------------------------------
    // Sequential logic (from clocked function `on_clock`)
    // -------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state <= 0;
            index <= 0;
            row <= 0;
            col <= 0;
            bitpos <= 0;
            head <= 0;
            pos <= 0;
            pair <= 0;
            jj <= 0;
            dd <= 0;
            kvcount <= 0;
            nrows <= 0;
            ropebase <= 0;
            pairs <= 0;
            weight_addr <= 0;
            last_run <= 0;
            run_id <= 0;
            poll <= 0;
            active <= 1'b0;
            cycles <= 0;
            report_cycles <= 0;
            memory_cycles <= 0;
            result_only <= 1'b0;
            positions <= 0;
            error_code <= 0;
            scale_q <= 0;
            scale_k <= 0;
            scale_v <= 0;
            scale_o <= 0;
            scale_attn <= 0;
            lane <= 0;
            acc0 <= 0;
            acc1 <= 0;
            term0 <= 0;
            term1 <= 0;
            add0 <= 0;
            add1 <= 0;
            add_carry <= 0;
            weight0 <= 0;
            weight1 <= 0;
            wb_cyc <= 1'b0;
            wb_stb <= 1'b0;
            wb_addr <= 0;
            response <= 0;
            read0 <= 0;
            read1 <= 0;
            quiet <= 0;
            pending <= 1'b0;
            ptag <= 0;
            pa <= 0;
            pb <= 0;
            emit_tag <= 0;
            emit_value <= 0;
            emit_index <= 0;
            after_emit <= 0;
            arb <= 0;
            sbuf <= 1'b0;
            sb_tag <= 0;
            sb_a <= 0;
            sb_b <= 0;
            line_go <= 1'b0;
            line_tag <= 0;
            line_a <= 0;
            line_b <= 0;
            sumsq0 <= 0;
            sumsq1 <= 0;
            rem0 <= 0;
            rem1 <= 0;
            quo0 <= 0;
            quo1 <= 0;
            divisor <= 0;
            root <= 0;
            rms <= 0;
            sub0 <= 0;
            sub1 <= 0;
            cmp0 <= 0;
            cmp1 <= 0;
            num_mag <= 0;
            num_sign <= 1'b0;
            out_mag <= 0;
            quant <= 0;
            twice <= 0;
            inc <= 0;
            exp_value <= 0;
            exp_denom <= 0;
            norm_pass <= 0;
            projection_stage <= 0;
            store_base <= 0;
            proj_scale <= 0;
            proj_tag <= 0;
            sample_q <= 0;
            weight_q <= 0;
            cos_q <= 0;
            sin_q <= 0;
            term2 <= 0;
            term3 <= 0;
            max_score <= 0;
            sc_index <= 0;
            mul_a <= 0;
            mul_b <= 0;
            mul_left <= 0;
            mul_right <= 0;
            mul_product <= 0;
            mul_bit <= 0;
            mul_return <= 0;
            scale_low_product <= 0;
            scale_high_carry <= 0;
            exp_z <= 0;
            exp_m <= 0;
            exp_j <= 0;
            exp_g <= 0;
            exp_h <= 0;
            exp_a2 <= 0;
            exp_a1 <= 0;
            exp_a0 <= 0;
            exp_b1 <= 0;
            exp_b0 <= 0;
            exp_p <= 0;
            exp_y <= 0;
            rne_num <= 0;
            rne_bits <= 0;
            rne_return <= 0;
            rne_q <= 0;
            rne_rem <= 0;
            rne_half <= 0;
            div_round_up <= 1'b0;
            sqrt_shift <= 0;
            sqrt_upper <= 1'b0;
            rne_up <= 1'b0;
            rne_result <= 0;
            vr2 <= 0;
            gr2 <= 0;
            ur2 <= 0;
        end else if (en) begin
            vr2 <= vec[(va & 8191)];
            gr2 <= gate[(ga & 8191)];
            ur2 <= up[(ua & 8191)];
            if (active) begin
                cycles <= (cycles + 1);
                if ((((state == 8) || (state == 300)) || (state == 301))) begin
                    report_cycles <= (report_cycles + 1);
                end
                if (((state == 200) || (state == 201))) begin
                    memory_cycles <= (memory_cycles + 1);
                end
            end
            pairs <= (head_dim / 2);
            kvcount <= __mul_noop(positions, kv);
            if ((state == 0)) begin
                if (calib) begin
                    wb_cyc <= 1'b1;
                    ptag <= 71;
                    pa <= hidden;
                    pb <= kv;
                    pending <= 1'b1;
                    state <= 1;
                end
            end
            if ((state == 1)) begin
                if (((poll == 0) && !pending)) begin
                    wb_addr <= 64;
                    wb_stb <= 1'b1;
                    response <= 2;
                    state <= 200;
                    quiet <= 0;
                end else if ((poll != 0)) begin
                    poll <= (poll - 1);
                end
            end
            if ((state == 2)) begin
                state <= 1;
                poll <= 8192;
                if (((((read0 >> 32) == 64'd1096045617) && ((read0 & {32{1'b1}}) != 0)) && ((read0 & {32{1'b1}}) != last_run))) begin
                    last_run <= (read0 & {32{1'b1}});
                    run_id <= (read0 & {32{1'b1}});
                    index <= 0;
                    active <= 1'b1;
                    cycles <= 0;
                    report_cycles <= 0;
                    memory_cycles <= 0;
                    error_code <= 0;
                    state <= 8;
                    positions <= (read1 & {32{1'b1}});
                    result_only <= ((read1 >> 32) != 0);
                    if ((((read1 & {32{1'b1}}) == 0) || ($signed({1'b0, (read1 & {32{1'b1}})}) > $signed(8)))) begin
                        error_code <= 10;
                        state <= 900;
                    end
                    if ((($signed({1'b0, (__mul_noop((read1 & {32{1'b1}}), kv) + hidden)}) > $signed(8192)) || ($signed(((__mul_noop((read1 & {32{1'b1}}), kv) + hidden) + 8)) > $signed(8192)))) begin
                        error_code <= 13;
                        state <= 900;
                    end
                end
            end
            if ((state == 3)) begin
                wb_addr <= (80 + index);
                wb_stb <= 1'b1;
                response <= 4;
                state <= 200;
                quiet <= 0;
            end
            if ((state == 4)) begin
                if ((index == 0)) begin
                    scale_q <= (read0 & {32{1'b1}});
                end
                if ((index == 1)) begin
                    scale_k <= (read0 & {32{1'b1}});
                end
                if ((index == 2)) begin
                    scale_v <= (read0 & {32{1'b1}});
                end
                if ((index == 3)) begin
                    scale_o <= (read0 & {32{1'b1}});
                end
                if ((index == 4)) begin
                    scale_attn <= (read0 & {32{1'b1}});
                    index <= 0;
                    state <= 10;
                end else begin
                    index <= (index + 1);
                    state <= 3;
                end
            end
            if ((state == 8)) begin
                if (!pending) begin
                    ptag <= 100;
                    pa <= run_id;
                    pb <= positions;
                    pending <= 1'b1;
                    state <= 3;
                end
            end
            if ((state == 10)) begin
                index <= 0;
                state <= 11;
            end
            if ((state == 11)) begin
                wb_addr <= (4096 + index);
                wb_stb <= 1'b1;
                response <= 12;
                state <= 200;
                quiet <= 0;
            end
            if ((state == 12)) begin
                gate[((__mul_noop(2, hidden) + index) & 8191)] <= (read0 & {32{1'b1}});
                if (((index + 1) == hidden)) begin
                    pos <= 0;
                    state <= 16;
                end else begin
                    index <= (index + 1);
                    state <= 11;
                end
            end
            if ((state == 16)) begin
                index <= 0;
                sc_index <= 0;
                state <= 17;
            end
            if ((state == 17)) begin
                wb_addr <= ((32768 + __mul_noop(pos, hidden)) + index);
                wb_stb <= 1'b1;
                response <= 18;
                state <= 200;
                quiet <= 0;
            end
            if ((state == 18)) begin
                vec[(index & 8191)] <= (read0 & {32{1'b1}});
                if (((index + 1) == hidden)) begin
                    index <= 0;
                    norm_pass <= 0;
                    state <= 20;
                end else begin
                    index <= (index + 1);
                    state <= 17;
                end
            end
            if ((state == 20)) begin
                index <= 0;
                sumsq0 <= 0;
                sumsq1 <= 0;
                state <= 1021;
            end
            if ((state == 21)) begin
                sample_q <= pick((norm_pass == 0), vr2, ur2);
                state <= 22;
            end
            if ((state == 22)) begin
                lane <= mag64(sample_q);
                state <= 23;
            end
            if ((state == 23)) begin
                mul_a <= lane;
                mul_b <= lane;
                mul_return <= 2023;
                state <= 400;
            end
            if ((state == 24)) begin
                sumsq0 <= add0;
                sumsq1 <= (sumsq1 + add_carry);
                if (((index + 1) == hidden)) begin
                    state <= 25;
                end else begin
                    index <= (index + 1);
                    state <= 1021;
                end
            end
            if ((state == 25)) begin
                rem0 <= 0;
                rem1 <= 0;
                quo0 <= 0;
                quo1 <= 0;
                divisor <= hidden;
                bitpos <= 73;
                state <= 26;
            end
            if ((state == 26)) begin
                if (($signed({1'b0, bitpos}) >= $signed(64))) begin
                    rem0 <= ((rem0 << 1) | pick((((sumsq1 >> (bitpos - 64)) & 1) != 0), 1, 0));
                end else begin
                    rem0 <= ((rem0 << 1) | pick((((sumsq0 >> bitpos) & 1) != 0), 1, 0));
                end
                rem1 <= ((rem1 << 1) | (rem0 >> 63));
                state <= 27;
            end
            if ((state == 27)) begin
                if (((rem1 != 0) || (rem0 >= divisor))) begin
                    if ((rem0 < divisor)) begin
                        rem1 <= (rem1 - 1);
                    end
                    rem0 <= (rem0 - divisor);
                    if (($signed({1'b0, bitpos}) >= $signed(64))) begin
                        quo1 <= (quo1 | (1 << (bitpos - 64)));
                    end else begin
                        quo0 <= (quo0 | (1 << bitpos));
                    end
                end
                if ((bitpos == 0)) begin
                    state <= 28;
                end else begin
                    bitpos <= (bitpos - 1);
                    state <= 26;
                end
            end
            if ((state == 28)) begin
                div_round_up <= (((rem0 << 1) > divisor) || (((rem0 << 1) == divisor) && ((quo0 & 1) != 0)));
                state <= 7028;
            end
            if ((state == 30)) begin
                quo0 <= add0;
                quo1 <= (quo1 + add_carry);
                state <= 31;
            end
            if ((state == 31)) begin
                add0 <= (quo0 + 42950);
                add_carry <= carry(quo0, 42950);
                state <= 7031;
            end
            if ((state == 32)) begin
                sqrt_upper <= ($signed({1'b0, bitpos}) >= $signed(64));
                sqrt_shift <= (pick(($signed({1'b0, bitpos}) >= $signed(64)), (bitpos - 64), (64 - bitpos)) & {32{1'b1}});
                state <= 8032;
            end
            if ((state == 33)) begin
                if (((rem1 > cmp1) || ((rem1 == cmp1) && (rem0 >= cmp0)))) begin
                    rem1 <= ((rem1 - cmp1) - pick((rem0 < cmp0), 1, 0));
                    rem0 <= (rem0 - cmp0);
                    root <= ((root << 1) | 1);
                end else begin
                    root <= (root << 1);
                end
                if ((bitpos == 0)) begin
                    state <= 34;
                end else begin
                    bitpos <= (bitpos - 2);
                    state <= 32;
                end
            end
            if ((state == 34)) begin
                rms <= root;
                index <= 0;
                state <= 1040;
            end
            if ((state == 40)) begin
                sample_q <= pick((norm_pass == 0), vr2, ur2);
                weight_q <= gr2;
                state <= 41;
            end
            if ((state == 41)) begin
                num_sign <= (sign64(sample_q) != sign64(weight_q));
                mul_a <= mag64(sample_q);
                mul_b <= mag64(weight_q);
                mul_return <= 2041;
                state <= 400;
            end
            if ((state == 42)) begin
                rem0 <= ((rem0 << 1) | pick((((num_mag >> bitpos) & 1) != 0), 1, 0));
                state <= 43;
            end
            if ((state == 43)) begin
                if ((rem0 >= rms)) begin
                    rem0 <= (rem0 - rms);
                    quo0 <= (quo0 | (1 << bitpos));
                end
                if ((bitpos == 0)) begin
                    state <= 44;
                end else begin
                    bitpos <= (bitpos - 1);
                    state <= 42;
                end
            end
            if ((state == 44)) begin
                div_round_up <= (((rem0 << 1) > rms) || (((rem0 << 1) == rms) && ((quo0 & 1) != 0)));
                state <= 7044;
            end
            if ((state == 45)) begin
                if (num_sign) begin
                    if (($signed({1'b0, out_mag}) > $signed(64'd2147483648))) begin
                        quant <= 64'd2147483648;
                    end else begin
                        quant <= (0 - out_mag);
                    end
                end else if (($signed({1'b0, out_mag}) > $signed(64'd2147483647))) begin
                    quant <= 64'd2147483647;
                end else begin
                    quant <= out_mag;
                end
                state <= 47;
            end
            if ((state == 46)) begin
                if (((index + 1) == hidden)) begin
                    if ((norm_pass == 0)) begin
                        state <= 50;
                    end else begin
                        state <= 170;
                    end
                end else begin
                    index <= (index + 1);
                    state <= 1040;
                end
            end
            if ((state == 47)) begin
                gate[(index & 8191)] <= (quant & {32{1'b1}});
                emit_tag <= pick((norm_pass == 0), 103, 111);
                emit_index <= index;
                emit_value <= (quant & {32{1'b1}});
                after_emit <= 46;
                state <= pick(result_only, 46, 300);
            end
            if ((state == 50)) begin
                projection_stage <= 0;
                store_base <= hidden;
                proj_scale <= scale_q;
                proj_tag <= 104;
                row <= 0;
                col <= 0;
                acc0 <= 0;
                nrows <= hidden;
                weight_addr <= 65536;
                state <= 71;
            end
            if ((state == 60)) begin
                projection_stage <= 1;
                store_base <= __mul_noop(pos, kv);
                proj_scale <= scale_k;
                proj_tag <= 105;
                row <= 0;
                col <= 0;
                acc0 <= 0;
                nrows <= kv;
                weight_addr <= 167936;
                state <= 71;
            end
            if ((state == 70)) begin
                projection_stage <= 2;
                store_base <= (hidden + __mul_noop(pos, kv));
                proj_scale <= scale_v;
                proj_tag <= 106;
                row <= 0;
                col <= 0;
                acc0 <= 0;
                nrows <= kv;
                weight_addr <= 193536;
                state <= 71;
            end
            if ((state == 71)) begin
                wb_addr <= weight_addr;
                wb_stb <= 1'b1;
                response <= 72;
                state <= 200;
                quiet <= 0;
            end
            if ((state == 72)) begin
                weight0 <= read0;
                weight1 <= read1;
                state <= 73;
            end
            if ((state == 73)) begin
                state <= 1074;
            end
            if ((state == 74)) begin
                term0 <= pick(((weight0 & 3) == 0), 0, pick(((weight0 & 3) == 2), (0 - extend(gr2)), extend(gr2)));
                state <= 75;
                weight0 <= ((weight0 >> 2) | (weight1 << 62));
                weight1 <= (weight1 >> 2);
                col <= (col + 1);
                if (((weight0 & 3) == 3)) begin
                    error_code <= 3;
                    state <= 900;
                end
            end
            if ((state == 75)) begin
                add0 <= (acc0 + term0);
                add_carry <= carry(acc0, term0);
                state <= 76;
            end
            if ((state == 76)) begin
                acc0 <= add0;
                if ((col == hidden)) begin
                    weight_addr <= (weight_addr + 1);
                    state <= 77;
                end else if (((col & 63) == 0)) begin
                    weight_addr <= (weight_addr + 1);
                    state <= 71;
                end else begin
                    state <= 1074;
                end
            end
            if ((state == 77)) begin
                mul_a <= pick(((acc0 >> 63) != 0), (0 - acc0), acc0);
                mul_b <= proj_scale;
                mul_return <= 2077;
                state <= 400;
            end
            if ((state == 78)) begin
                if (((acc0 >> 63) != 0)) begin
                    if (($signed({1'b0, quant}) > $signed(64'd2147483648))) begin
                        quant <= 64'd2147483648;
                    end else begin
                        quant <= (0 - quant);
                    end
                end else if (($signed({1'b0, quant}) > $signed(64'd2147483647))) begin
                    quant <= 64'd2147483647;
                end
                state <= 79;
            end
            if ((state == 79)) begin
                if ((projection_stage == 0)) begin
                    gate[((store_base + row) & 8191)] <= (quant & {32{1'b1}});
                end
                if ((projection_stage == 1)) begin
                    up[((store_base + row) & 8191)] <= (quant & {32{1'b1}});
                end
                if ((projection_stage == 2)) begin
                    vec[((store_base + row) & 8191)] <= (quant & {32{1'b1}});
                end
                if ((projection_stage == 3)) begin
                    gate[((store_base + row) & 8191)] <= (quant & {32{1'b1}});
                end
                emit_tag <= proj_tag;
                emit_index <= row;
                emit_value <= (quant & {32{1'b1}});
                after_emit <= 800;
                state <= pick(result_only, 800, 300);
            end
            if ((state == 90)) begin
                ropebase <= ((321536 + __mul_noop(pos, head_dim)) + __mul_noop(2, pair));
                state <= 91;
            end
            if ((state == 91)) begin
                wb_addr <= ropebase;
                wb_stb <= 1'b1;
                response <= 92;
                state <= 200;
                quiet <= 0;
            end
            if ((state == 92)) begin
                cos_q <= (read0 & {32{1'b1}});
                state <= 93;
            end
            if ((state == 93)) begin
                wb_addr <= (ropebase + 1);
                wb_stb <= 1'b1;
                response <= 94;
                state <= 200;
                quiet <= 0;
            end
            if ((state == 94)) begin
                sin_q <= (read0 & {32{1'b1}});
                state <= 1095;
            end
            if ((state == 95)) begin
                sample_q <= gr2;
                state <= 1096;
            end
            if ((state == 96)) begin
                lane <= gr2;
                state <= 97;
            end
            if ((state == 97)) begin
                mul_a <= extend(sample_q);
                mul_b <= extend(cos_q);
                mul_return <= 2097;
                state <= 400;
            end
            if ((state == 98)) begin
                mul_a <= extend(lane);
                mul_b <= extend(sin_q);
                mul_return <= 2098;
                state <= 400;
            end
            if ((state == 99)) begin
                num_mag <= (term0 - term1);
                state <= 100;
            end
            if ((state == 100)) begin
                num_sign <= ((num_mag >> 63) != 0);
                state <= 109;
            end
            if ((state == 101)) begin
                rne_num <= out_mag;
                rne_bits <= 16;
                rne_return <= 4101;
                state <= 500;
            end
            if ((state == 102)) begin
                if (num_sign) begin
                    if (($signed({1'b0, quant}) > $signed(64'd2147483648))) begin
                        quant <= 64'd2147483648;
                    end else begin
                        quant <= (0 - quant);
                    end
                end else if (($signed({1'b0, quant}) > $signed(64'd2147483647))) begin
                    quant <= 64'd2147483647;
                end
                state <= 112;
            end
            if ((state == 103)) begin
                mul_a <= extend(sample_q);
                mul_b <= extend(sin_q);
                mul_return <= 2103;
                state <= 400;
            end
            if ((state == 104)) begin
                num_mag <= (term2 + term3);
                state <= 105;
            end
            if ((state == 105)) begin
                num_sign <= ((num_mag >> 63) != 0);
                state <= 106;
            end
            if ((state == 106)) begin
                out_mag <= pick(num_sign, (0 - num_mag), num_mag);
                state <= 107;
            end
            if ((state == 107)) begin
                rne_num <= out_mag;
                rne_bits <= 16;
                rne_return <= 4107;
                state <= 500;
            end
            if ((state == 108)) begin
                gate[((((hidden + __mul_noop(head, head_dim)) + pair) + pairs) & 8191)] <= (quant & {32{1'b1}});
                if (((head + 1) == heads)) begin
                    if (((pair + 1) == pairs)) begin
                        index <= 0;
                        state <= 1110;
                    end else begin
                        pair <= (pair + 1);
                        head <= 0;
                        state <= 90;
                    end
                end else begin
                    head <= (head + 1);
                    state <= 1095;
                end
            end
            if ((state == 109)) begin
                out_mag <= pick(num_sign, (0 - num_mag), num_mag);
                state <= 101;
            end
            if ((state == 110)) begin
                emit_tag <= 107;
                emit_index <= index;
                emit_value <= gr2;
                after_emit <= 111;
                state <= pick(result_only, 111, 300);
            end
            if ((state == 111)) begin
                if (((index + 1) == hidden)) begin
                    index <= 0;
                    pair <= 0;
                    head <= 0;
                    state <= 115;
                end else begin
                    index <= (index + 1);
                    state <= 1110;
                end
            end
            if ((state == 112)) begin
                gate[(((hidden + __mul_noop(head, head_dim)) + pair) & 8191)] <= (quant & {32{1'b1}});
                mul_a <= extend(lane);
                mul_b <= extend(cos_q);
                mul_return <= 2112;
                state <= 400;
            end
            if ((state == 113)) begin
                if (num_sign) begin
                    if (($signed({1'b0, quant}) > $signed(64'd2147483648))) begin
                        quant <= 64'd2147483648;
                    end else begin
                        quant <= (0 - quant);
                    end
                end else if (($signed({1'b0, quant}) > $signed(64'd2147483647))) begin
                    quant <= 64'd2147483647;
                end
                state <= 108;
            end
            if ((state == 115)) begin
                ropebase <= ((321536 + __mul_noop(pos, head_dim)) + __mul_noop(2, pair));
                state <= 116;
            end
            if ((state == 116)) begin
                wb_addr <= ropebase;
                wb_stb <= 1'b1;
                response <= 117;
                state <= 200;
                quiet <= 0;
            end
            if ((state == 117)) begin
                cos_q <= (read0 & {32{1'b1}});
                state <= 118;
            end
            if ((state == 118)) begin
                wb_addr <= (ropebase + 1);
                wb_stb <= 1'b1;
                response <= 119;
                state <= 200;
                quiet <= 0;
            end
            if ((state == 119)) begin
                sin_q <= (read0 & {32{1'b1}});
                state <= 1120;
            end
            if ((state == 120)) begin
                sample_q <= ur2;
                state <= 1121;
            end
            if ((state == 121)) begin
                lane <= ur2;
                state <= 122;
            end
            if ((state == 122)) begin
                mul_a <= extend(sample_q);
                mul_b <= extend(cos_q);
                mul_return <= 2122;
                state <= 400;
            end
            if ((state == 123)) begin
                mul_a <= extend(lane);
                mul_b <= extend(sin_q);
                mul_return <= 2123;
                state <= 400;
            end
            if ((state == 124)) begin
                num_mag <= (term0 - term1);
                state <= 125;
            end
            if ((state == 125)) begin
                num_sign <= ((num_mag >> 63) != 0);
                state <= 134;
            end
            if ((state == 126)) begin
                rne_num <= out_mag;
                rne_bits <= 16;
                rne_return <= 4126;
                state <= 500;
            end
            if ((state == 127)) begin
                if (num_sign) begin
                    if (($signed({1'b0, quant}) > $signed(64'd2147483648))) begin
                        quant <= 64'd2147483648;
                    end else begin
                        quant <= (0 - quant);
                    end
                end else if (($signed({1'b0, quant}) > $signed(64'd2147483647))) begin
                    quant <= 64'd2147483647;
                end
                state <= 137;
            end
            if ((state == 128)) begin
                mul_a <= extend(sample_q);
                mul_b <= extend(sin_q);
                mul_return <= 2128;
                state <= 400;
            end
            if ((state == 129)) begin
                num_mag <= (term2 + term3);
                state <= 130;
            end
            if ((state == 130)) begin
                num_sign <= ((num_mag >> 63) != 0);
                state <= 131;
            end
            if ((state == 131)) begin
                out_mag <= pick(num_sign, (0 - num_mag), num_mag);
                state <= 132;
            end
            if ((state == 132)) begin
                rne_num <= out_mag;
                rne_bits <= 16;
                rne_return <= 4132;
                state <= 500;
            end
            if ((state == 133)) begin
                up[((((__mul_noop(pos, kv) + __mul_noop(head, head_dim)) + pair) + pairs) & 8191)] <= (quant & {32{1'b1}});
                if (((head + 1) == kv_heads)) begin
                    if (((pair + 1) == pairs)) begin
                        index <= 0;
                        state <= 1135;
                    end else begin
                        pair <= (pair + 1);
                        head <= 0;
                        state <= 115;
                    end
                end else begin
                    head <= (head + 1);
                    state <= 1120;
                end
            end
            if ((state == 134)) begin
                out_mag <= pick(num_sign, (0 - num_mag), num_mag);
                state <= 126;
            end
            if ((state == 135)) begin
                emit_tag <= 108;
                emit_index <= index;
                emit_value <= ur2;
                after_emit <= 136;
                state <= pick(result_only, 136, 300);
            end
            if ((state == 136)) begin
                if (((index + 1) == kv)) begin
                    head <= 0;
                    state <= 140;
                end else begin
                    index <= (index + 1);
                    state <= 1135;
                end
            end
            if ((state == 137)) begin
                up[(((__mul_noop(pos, kv) + __mul_noop(head, head_dim)) + pair) & 8191)] <= (quant & {32{1'b1}});
                mul_a <= extend(lane);
                mul_b <= extend(cos_q);
                mul_return <= 2137;
                state <= 400;
            end
            if ((state == 138)) begin
                if (num_sign) begin
                    if (($signed({1'b0, quant}) > $signed(64'd2147483648))) begin
                        quant <= 64'd2147483648;
                    end else begin
                        quant <= (0 - quant);
                    end
                end else if (($signed({1'b0, quant}) > $signed(64'd2147483647))) begin
                    quant <= 64'd2147483647;
                end
                state <= 133;
            end
            if ((state == 140)) begin
                jj <= 0;
                col <= 0;
                acc0 <= 0;
                acc1 <= 0;
                state <= 1141;
            end
            if ((state == 141)) begin
                mul_a <= extend(gr2);
                mul_b <= extend(ur2);
                mul_return <= 2141;
                state <= 400;
            end
            if ((state == 142)) begin
                add0 <= (acc0 + lane);
                add_carry <= carry(acc0, lane);
                state <= 3142;
            end
            if ((state == 143)) begin
                acc0 <= add0;
                acc1 <= add1;
                if (((col + 1) == head_dim)) begin
                    state <= 144;
                end else begin
                    col <= (col + 1);
                    state <= 1141;
                end
            end
            if ((state == 144)) begin
                if (((acc1 >> 63) != 0)) begin
                    out_mag <= (0 - acc0);
                    rem1 <= ((0 - acc1) - pick((acc0 != 0), 1, 0));
                end else begin
                    out_mag <= acc0;
                    rem1 <= acc1;
                end
                state <= 145;
            end
            if ((state == 145)) begin
                mul_a <= scale_attn;
                mul_b <= (out_mag & 64'd4294967295);
                mul_return <= 2145;
                state <= 400;
            end
            if ((state == 146)) begin
                div_round_up <= (($signed({1'b0, rem0}) > $signed(64'd2147483648)) || ((rem0 == 64'd2147483648) && ((((add1 << 32) | add0) & 1) != 0)));
                state <= 7146;
            end
            if ((state == 147)) begin
                if (((acc1 >> 63) != 0)) begin
                    if (($signed({1'b0, quant}) > $signed(64'd2147483648))) begin
                        quant <= 64'd2147483648;
                    end else begin
                        quant <= (0 - quant);
                    end
                end else if (($signed({1'b0, quant}) > $signed(64'd2147483647))) begin
                    quant <= 64'd2147483647;
                end
                state <= 148;
            end
            if ((state == 148)) begin
                sample_q <= (quant & {32{1'b1}});
                state <= 169;
            end
            if ((state == 149)) begin
                sc_index <= (sc_index + 1);
                if ((jj < pos)) begin
                    jj <= (jj + 1);
                    col <= 0;
                    acc0 <= 0;
                    acc1 <= 0;
                    state <= 1141;
                end else begin
                    jj <= 0;
                    state <= 1150;
                end
            end
            if ((state == 150)) begin
                max_score <= vr2;
                state <= 151;
            end
            if ((state == 151)) begin
                if ((jj < pos)) begin
                    jj <= (jj + 1);
                    state <= 1152;
                end else begin
                    jj <= 0;
                    exp_denom <= 0;
                    state <= 1154;
                end
            end
            if ((state == 152)) begin
                if (sgt(extend(vr2), extend(max_score))) begin
                    max_score <= vr2;
                end
                state <= 151;
            end
            if ((state == 154)) begin
                exp_z <= ((0 - (vr2 - max_score)) & 64'd4294967295);
                state <= 700;
            end
            if ((state == 155)) begin
                vec[(((hidden + kvcount) + jj) & 8191)] <= exp_value;
                exp_denom <= (exp_denom + exp_value);
                state <= 156;
            end
            if ((state == 156)) begin
                if ((jj < pos)) begin
                    jj <= (jj + 1);
                    state <= 1154;
                end else begin
                    jj <= 0;
                    dd <= 0;
                    state <= 160;
                end
            end
            if ((state == 157)) begin
                mul_a <= extend(sample_q);
                mul_b <= vr2;
                mul_return <= 2157;
                state <= 400;
            end
            if ((state == 158)) begin
                up[(((kvcount + __mul_noop(head, head_dim)) + dd) & 8191)] <= (quant & {32{1'b1}});
                emit_tag <= 110;
                emit_index <= (__mul_noop(head, head_dim) + dd);
                emit_value <= (quant & {32{1'b1}});
                after_emit <= 168;
                state <= pick(result_only, 168, 300);
            end
            if ((state == 160)) begin
                acc0 <= 0;
                state <= 1161;
            end
            if ((state == 161)) begin
                sample_q <= vr2;
                state <= 1157;
            end
            if ((state == 162)) begin
                acc0 <= (acc0 + lane);
                if ((jj < pos)) begin
                    jj <= (jj + 1);
                    state <= 1161;
                end else begin
                    jj <= 0;
                    state <= 163;
                end
            end
            if ((state == 163)) begin
                num_sign <= ((acc0 >> 63) != 0);
                num_mag <= pick(((acc0 >> 63) != 0), (0 - acc0), acc0);
                rem0 <= 0;
                quo0 <= 0;
                bitpos <= 63;
                state <= 164;
            end
            if ((state == 164)) begin
                rem0 <= ((rem0 << 1) | pick((((num_mag >> bitpos) & 1) != 0), 1, 0));
                state <= 165;
            end
            if ((state == 165)) begin
                if ((rem0 >= exp_denom)) begin
                    rem0 <= (rem0 - exp_denom);
                    quo0 <= (quo0 | (1 << bitpos));
                end
                if ((bitpos == 0)) begin
                    state <= 166;
                end else begin
                    bitpos <= (bitpos - 1);
                    state <= 164;
                end
            end
            if ((state == 166)) begin
                div_round_up <= (((rem0 << 1) > exp_denom) || (((rem0 << 1) == exp_denom) && ((quo0 & 1) != 0)));
                state <= 7166;
            end
            if ((state == 167)) begin
                if (num_sign) begin
                    if (($signed({1'b0, out_mag}) > $signed(64'd2147483648))) begin
                        quant <= 64'd2147483648;
                    end else begin
                        quant <= (0 - out_mag);
                    end
                end else if (($signed({1'b0, out_mag}) > $signed(64'd2147483647))) begin
                    quant <= 64'd2147483647;
                end else begin
                    quant <= out_mag;
                end
                state <= 158;
            end
            if ((state == 168)) begin
                if (((dd + 1) == head_dim)) begin
                    if (((head + 1) == heads)) begin
                        index <= 0;
                        state <= 172;
                    end else begin
                        head <= (head + 1);
                        state <= 140;
                    end
                end else begin
                    dd <= (dd + 1);
                    state <= 160;
                end
            end
            if ((state == 169)) begin
                vec[(((hidden + kvcount) + jj) & 8191)] <= sample_q;
                emit_tag <= 109;
                emit_index <= sc_index;
                emit_value <= sample_q;
                after_emit <= 149;
                state <= pick(result_only, 149, 300);
            end
            if ((state == 170)) begin
                projection_stage <= 3;
                store_base <= hidden;
                proj_scale <= scale_o;
                proj_tag <= 112;
                row <= 0;
                col <= 0;
                acc0 <= 0;
                nrows <= hidden;
                weight_addr <= 219136;
                state <= 71;
            end
            if ((state == 172)) begin
                index <= 0;
                state <= 173;
            end
            if ((state == 173)) begin
                wb_addr <= (8192 + index);
                wb_stb <= 1'b1;
                response <= 174;
                state <= 200;
                quiet <= 0;
            end
            if ((state == 174)) begin
                gate[(index & 8191)] <= (read0 & {32{1'b1}});
                if (((index + 1) == hidden)) begin
                    index <= 0;
                    norm_pass <= 1;
                    state <= 20;
                end else begin
                    index <= (index + 1);
                    state <= 173;
                end
            end
            if ((state == 180)) begin
                lane <= (extend(vr2) + extend(gr2));
                state <= 181;
            end
            if ((state == 181)) begin
                if (((lane >> 63) != 0)) begin
                    if (($signed({1'b0, lane}) < $signed(64'd18446744071562067968))) begin
                        quant <= 64'd2147483648;
                    end else begin
                        quant <= lane;
                    end
                end else if (($signed({1'b0, lane}) > $signed(64'd2147483647))) begin
                    quant <= 64'd2147483647;
                end else begin
                    quant <= lane;
                end
                state <= 182;
            end
            if ((state == 182)) begin
                emit_tag <= 113;
                emit_index <= index;
                emit_value <= (quant & {32{1'b1}});
                after_emit <= 183;
                state <= 300;
            end
            if ((state == 183)) begin
                if (((index + 1) == hidden)) begin
                    state <= 184;
                end else begin
                    index <= (index + 1);
                    state <= 1180;
                end
            end
            if ((state == 184)) begin
                if (((pos + 1) == positions)) begin
                    active <= 1'b0;
                    state <= 600;
                end else begin
                    pos <= (pos + 1);
                    state <= 16;
                end
            end
            if ((state == 200)) begin
                quiet <= (quiet + 1);
                if (!stall) begin
                    wb_stb <= 1'b0;
                    state <= 201;
                end
                if (ack) begin
                    read0 <= rdata_lo;
                    read1 <= rdata_hi;
                    wb_stb <= 1'b0;
                    if ((response == 0)) begin
                        state <= 0;
                    end else if ((response == 2)) begin
                        state <= 2;
                    end else if ((response == 4)) begin
                        state <= 4;
                    end else if ((response == 12)) begin
                        state <= 12;
                    end else if ((response == 18)) begin
                        state <= 18;
                    end else if ((response == 72)) begin
                        state <= 72;
                    end else if ((response == 92)) begin
                        state <= 92;
                    end else if ((response == 94)) begin
                        state <= 94;
                    end else if ((response == 117)) begin
                        state <= 117;
                    end else if ((response == 119)) begin
                        state <= 119;
                    end else if ((response == 174)) begin
                        state <= 174;
                    end else if ((response == 999)) begin
                        state <= 999;
                    end else begin
                        error_code <= 4;
                        state <= 900;
                    end
                end
                if (($signed({1'b0, quiet}) >= $signed(16777216))) begin
                    error_code <= 4;
                    wb_stb <= 1'b0;
                    state <= 900;
                end
            end
            if ((state == 201)) begin
                quiet <= (quiet + 1);
                if (ack) begin
                    read0 <= rdata_lo;
                    read1 <= rdata_hi;
                    if ((response == 0)) begin
                        state <= 0;
                    end else if ((response == 2)) begin
                        state <= 2;
                    end else if ((response == 4)) begin
                        state <= 4;
                    end else if ((response == 12)) begin
                        state <= 12;
                    end else if ((response == 18)) begin
                        state <= 18;
                    end else if ((response == 72)) begin
                        state <= 72;
                    end else if ((response == 92)) begin
                        state <= 92;
                    end else if ((response == 94)) begin
                        state <= 94;
                    end else if ((response == 117)) begin
                        state <= 117;
                    end else if ((response == 119)) begin
                        state <= 119;
                    end else if ((response == 174)) begin
                        state <= 174;
                    end else if ((response == 999)) begin
                        state <= 999;
                    end else begin
                        error_code <= 4;
                        state <= 900;
                    end
                end
                if (($signed({1'b0, quiet}) >= $signed(16777216))) begin
                    error_code <= 4;
                    state <= 900;
                end
            end
            if ((state == 300)) begin
                if (!pending) begin
                    ptag <= emit_tag;
                    pa <= emit_index;
                    pb <= emit_value;
                    pending <= 1'b1;
                    state <= 301;
                end
            end
            if ((state == 301)) begin
                if (!pending) begin
                    if ((after_emit == 0)) begin
                        state <= 0;
                    end else if ((after_emit == 46)) begin
                        state <= 46;
                    end else if ((after_emit == 111)) begin
                        state <= 111;
                    end else if ((after_emit == 136)) begin
                        state <= 136;
                    end else if ((after_emit == 149)) begin
                        state <= 149;
                    end else if ((after_emit == 168)) begin
                        state <= 168;
                    end else if ((after_emit == 183)) begin
                        state <= 183;
                    end else if ((after_emit == 800)) begin
                        state <= 800;
                    end else if ((after_emit == 999)) begin
                        state <= 999;
                    end else begin
                        error_code <= 4;
                        state <= 900;
                    end
                end
            end
            if ((state == 400)) begin
                mul_product <= 0;
                mul_left <= mul_a;
                mul_right <= mul_b;
                mul_bit <= 0;
                state <= 401;
            end
            if ((state == 401)) begin
                mul_product <= (mul_product + pick(((mul_right & 1) != 0), mul_left, 0));
                mul_left <= (mul_left << 1);
                mul_right <= (mul_right >> 1);
                if ((mul_bit == 63)) begin
                    if ((mul_return == 0)) begin
                        state <= 0;
                    end else if ((mul_return == 701)) begin
                        state <= 701;
                    end else if ((mul_return == 703)) begin
                        state <= 703;
                    end else if ((mul_return == 705)) begin
                        state <= 705;
                    end else if ((mul_return == 707)) begin
                        state <= 707;
                    end else if ((mul_return == 709)) begin
                        state <= 709;
                    end else if ((mul_return == 711)) begin
                        state <= 711;
                    end else if ((mul_return == 713)) begin
                        state <= 713;
                    end else if ((mul_return == 715)) begin
                        state <= 715;
                    end else if ((mul_return == 717)) begin
                        state <= 717;
                    end else if ((mul_return == 999)) begin
                        state <= 999;
                    end else if ((mul_return == 2023)) begin
                        state <= 2023;
                    end else if ((mul_return == 2041)) begin
                        state <= 2041;
                    end else if ((mul_return == 2077)) begin
                        state <= 2077;
                    end else if ((mul_return == 2097)) begin
                        state <= 2097;
                    end else if ((mul_return == 2098)) begin
                        state <= 2098;
                    end else if ((mul_return == 2103)) begin
                        state <= 2103;
                    end else if ((mul_return == 2112)) begin
                        state <= 2112;
                    end else if ((mul_return == 2122)) begin
                        state <= 2122;
                    end else if ((mul_return == 2123)) begin
                        state <= 2123;
                    end else if ((mul_return == 2128)) begin
                        state <= 2128;
                    end else if ((mul_return == 2137)) begin
                        state <= 2137;
                    end else if ((mul_return == 2141)) begin
                        state <= 2141;
                    end else if ((mul_return == 2145)) begin
                        state <= 2145;
                    end else if ((mul_return == 2146)) begin
                        state <= 2146;
                    end else if ((mul_return == 2147)) begin
                        state <= 2147;
                    end else if ((mul_return == 2157)) begin
                        state <= 2157;
                    end else begin
                        error_code <= 4;
                        state <= 900;
                    end
                end else begin
                    mul_bit <= (mul_bit + 1);
                end
            end
            if ((state == 500)) begin
                rne_q <= (rne_num >> rne_bits);
                rne_rem <= (rne_num & ((1 << rne_bits) - 1));
                rne_half <= (1 << (rne_bits - 1));
                state <= 501;
            end
            if ((state == 501)) begin
                rne_up <= ((rne_rem > rne_half) || ((rne_rem == rne_half) && ((rne_q & 1) != 0)));
                state <= 502;
            end
            if ((state == 502)) begin
                rne_result <= (rne_q + pick(rne_up, 1, 0));
                if ((rne_return == 0)) begin
                    state <= 0;
                end else if ((rne_return == 999)) begin
                    state <= 999;
                end else if ((rne_return == 4101)) begin
                    state <= 4101;
                end else if ((rne_return == 4107)) begin
                    state <= 4107;
                end else if ((rne_return == 4126)) begin
                    state <= 4126;
                end else if ((rne_return == 4132)) begin
                    state <= 4132;
                end else if ((rne_return == 4718)) begin
                    state <= 4718;
                end else if ((rne_return == 6077)) begin
                    state <= 6077;
                end else begin
                    error_code <= 4;
                    state <= 900;
                end
            end
            if ((state == 600)) begin
                if (!pending) begin
                    ptag <= 99;
                    pa <= run_id;
                    pb <= cycles;
                    pending <= 1'b1;
                    state <= 601;
                end
            end
            if ((state == 601)) begin
                if (!pending) begin
                    ptag <= 118;
                    pa <= 0;
                    pb <= report_cycles;
                    pending <= 1'b1;
                    state <= 602;
                end
            end
            if ((state == 602)) begin
                if (!pending) begin
                    ptag <= 118;
                    pa <= 1;
                    pb <= memory_cycles;
                    pending <= 1'b1;
                    state <= 603;
                end
            end
            if ((state == 603)) begin
                if (!pending) begin
                    ptag <= 122;
                    pa <= run_id;
                    pb <= 0;
                    pending <= 1'b1;
                    state <= 1;
                    poll <= 8192;
                end
            end
            if ((state == 700)) begin
                if (($signed({1'b0, exp_z}) >= $signed(772244))) begin
                    exp_value <= 0;
                    state <= 155;
                end else begin
                    mul_a <= exp_z;
                    mul_b <= 64'd6196328019;
                    mul_return <= 701;
                    state <= 400;
                end
            end
            if ((state == 701)) begin
                exp_m <= ((mul_product >> 48) & {32{1'b1}});
                exp_j <= (((mul_product >> 44) & 15) & {32{1'b1}});
                exp_g <= ((mul_product & 64'd17592186044415) >>> 16);
                state <= 702;
            end
            if ((state == 702)) begin
                mul_a <= exp_g;
                mul_b <= exp_g;
                mul_return <= 703;
                state <= 400;
            end
            if ((state == 703)) begin
                exp_h <= (mul_product >> 32);
                state <= 704;
            end
            if ((state == 704)) begin
                mul_a <= 661577;
                mul_b <= exp_h;
                mul_return <= 705;
                state <= 400;
            end
            if ((state == 705)) begin
                exp_a2 <= ((mul_product >> 32) + 41309550);
                state <= 706;
            end
            if ((state == 706)) begin
                mul_a <= exp_a2;
                mul_b <= exp_h;
                mul_return <= 707;
                state <= 400;
            end
            if ((state == 707)) begin
                exp_a1 <= ((mul_product >> 32) + 64'd1031764991);
                state <= 708;
            end
            if ((state == 708)) begin
                mul_a <= exp_a1;
                mul_b <= exp_h;
                mul_return <= 709;
                state <= 400;
            end
            if ((state == 709)) begin
                exp_a0 <= ((mul_product >> 32) + 64'd4294967296);
                state <= 710;
            end
            if ((state == 710)) begin
                mul_a <= 5726720;
                mul_b <= exp_h;
                mul_return <= 711;
                state <= 400;
            end
            if ((state == 711)) begin
                exp_b1 <= ((mul_product >> 32) + 238388332);
                state <= 712;
            end
            if ((state == 712)) begin
                mul_a <= exp_b1;
                mul_b <= exp_h;
                mul_return <= 713;
                state <= 400;
            end
            if ((state == 713)) begin
                exp_b0 <= ((mul_product >> 32) + 64'd2977044472);
                state <= 714;
            end
            if ((state == 714)) begin
                mul_a <= exp_g;
                mul_b <= exp_b0;
                mul_return <= 715;
                state <= 400;
            end
            if ((state == 715)) begin
                exp_p <= (exp_a0 - (mul_product >> 32));
                state <= 716;
            end
            if ((state == 716)) begin
                if ((exp_j == 0)) begin
                    exp_y <= exp_p;
                    state <= 718;
                end else begin
                    mul_a <= exp_lut(exp_j);
                    mul_b <= exp_p;
                    mul_return <= 717;
                    state <= 400;
                end
            end
            if ((state == 717)) begin
                exp_y <= (mul_product >> 32);
                state <= 718;
            end
            if ((state == 718)) begin
                rne_num <= exp_y;
                rne_bits <= (16 + exp_m);
                rne_return <= 4718;
                state <= 500;
            end
            if ((state == 800)) begin
                acc0 <= 0;
                col <= 0;
                if (((row + 1) == nrows)) begin
                    if ((projection_stage == 0)) begin
                        state <= 60;
                    end else if ((projection_stage == 1)) begin
                        state <= 70;
                    end else if ((projection_stage == 2)) begin
                        index <= 0;
                        pair <= 0;
                        head <= 0;
                        state <= 90;
                    end else begin
                        index <= 0;
                        state <= 1180;
                    end
                end else begin
                    row <= (row + 1);
                    state <= 71;
                end
            end
            if ((state == 900)) begin
                active <= 1'b0;
                wb_cyc <= 1'b0;
                wb_stb <= 1'b0;
                if (!pending) begin
                    ptag <= 69;
                    pa <= error_code;
                    pb <= run_id;
                    pending <= 1'b1;
                    state <= 901;
                end
            end
            if ((state == 1021)) begin
                state <= 21;
            end
            if ((state == 1040)) begin
                state <= 40;
            end
            if ((state == 1074)) begin
                state <= 74;
            end
            if ((state == 1095)) begin
                state <= 95;
            end
            if ((state == 1096)) begin
                state <= 96;
            end
            if ((state == 1110)) begin
                state <= 110;
            end
            if ((state == 1120)) begin
                state <= 120;
            end
            if ((state == 1121)) begin
                state <= 121;
            end
            if ((state == 1135)) begin
                state <= 135;
            end
            if ((state == 1141)) begin
                state <= 141;
            end
            if ((state == 1150)) begin
                state <= 150;
            end
            if ((state == 1152)) begin
                state <= 152;
            end
            if ((state == 1154)) begin
                state <= 154;
            end
            if ((state == 1157)) begin
                state <= 157;
            end
            if ((state == 1161)) begin
                state <= 161;
            end
            if ((state == 1180)) begin
                state <= 180;
            end
            if ((state == 2023)) begin
                add0 <= (sumsq0 + mul_product);
                add_carry <= carry(sumsq0, mul_product);
                state <= 24;
            end
            if ((state == 2041)) begin
                num_mag <= (mul_product << 16);
                rem0 <= 0;
                quo0 <= 0;
                bitpos <= 63;
                state <= 42;
            end
            if ((state == 2077)) begin
                rne_num <= mul_product;
                rne_bits <= 16;
                rne_return <= 6077;
                state <= 500;
            end
            if ((state == 2097)) begin
                term0 <= mul_product;
                state <= 98;
            end
            if ((state == 2098)) begin
                term1 <= mul_product;
                state <= 99;
            end
            if ((state == 2103)) begin
                term3 <= mul_product;
                state <= 104;
            end
            if ((state == 2112)) begin
                term2 <= mul_product;
                state <= 103;
            end
            if ((state == 2122)) begin
                term0 <= mul_product;
                state <= 123;
            end
            if ((state == 2123)) begin
                term1 <= mul_product;
                state <= 124;
            end
            if ((state == 2128)) begin
                term3 <= mul_product;
                state <= 129;
            end
            if ((state == 2137)) begin
                term2 <= mul_product;
                state <= 128;
            end
            if ((state == 2141)) begin
                lane <= mul_product;
                state <= 142;
            end
            if ((state == 2145)) begin
                scale_low_product <= mul_product;
                mul_a <= scale_attn;
                mul_b <= (out_mag >> 32);
                mul_return <= 2146;
                state <= 400;
            end
            if ((state == 2146)) begin
                rem0 <= (scale_low_product & 64'd4294967295);
                add0 <= ((mul_product + (scale_low_product >> 32)) & 64'd4294967295);
                scale_high_carry <= ((mul_product + (scale_low_product >> 32)) >> 32);
                mul_a <= scale_attn;
                mul_b <= rem1;
                mul_return <= 2147;
                state <= 400;
            end
            if ((state == 2147)) begin
                add1 <= (mul_product + scale_high_carry);
                state <= 146;
            end
            if ((state == 2157)) begin
                lane <= mul_product;
                state <= 162;
            end
            if ((state == 3142)) begin
                add1 <= ((acc1 + pick(((lane >> 63) != 0), 64'd18446744073709551615, 0)) + add_carry);
                state <= 143;
            end
            if ((state == 4101)) begin
                quant <= rne_result;
                state <= 102;
            end
            if ((state == 4107)) begin
                quant <= rne_result;
                state <= 113;
            end
            if ((state == 4126)) begin
                quant <= rne_result;
                state <= 127;
            end
            if ((state == 4132)) begin
                quant <= rne_result;
                state <= 138;
            end
            if ((state == 4718)) begin
                exp_value <= (rne_result & {32{1'b1}});
                state <= 155;
            end
            if ((state == 6077)) begin
                quant <= rne_result;
                state <= 78;
            end
            if ((state == 7028)) begin
                add0 <= (quo0 + pick(div_round_up, 1, 0));
                add_carry <= carry(quo0, pick(div_round_up, 1, 0));
                state <= 30;
            end
            if ((state == 7031)) begin
                rem1 <= (((quo1 + add_carry) << 32) | (add0 >> 32));
                rem0 <= (add0 << 32);
                root <= 0;
                bitpos <= 94;
                state <= 32;
            end
            if ((state == 7044)) begin
                out_mag <= (quo0 + pick(div_round_up, 1, 0));
                state <= 45;
            end
            if ((state == 7146)) begin
                quant <= (((add1 << 32) | add0) + pick(div_round_up, 1, 0));
                state <= 147;
            end
            if ((state == 7166)) begin
                out_mag <= (quo0 + pick(div_round_up, 1, 0));
                state <= 167;
            end
            if ((state == 8032)) begin
                if (sqrt_upper) begin
                    cmp1 <= (((root << 2) | 1) << sqrt_shift);
                    cmp0 <= 0;
                end else begin
                    cmp1 <= (((root << 2) | 1) >>> sqrt_shift);
                    cmp0 <= (((root << 2) | 1) << bitpos);
                end
                state <= 33;
            end
            if ((active && !calib)) begin
                error_code <= 2;
                state <= 900;
            end
            if (((ack && (state != 200)) && (state != 201))) begin
                error_code <= 5;
                state <= 900;
            end
            line_go <= 1'b0;
            if (s_go) begin
                sbuf <= 1'b1;
                sb_tag <= s_tag;
                sb_a <= s_a;
                sb_b <= s_b;
            end
            if ((arb == 0)) begin
                if ((line_idle && sbuf)) begin
                    line_go <= 1'b1;
                    line_tag <= sb_tag;
                    line_a <= sb_a;
                    line_b <= sb_b;
                    sbuf <= 1'b0;
                    arb <= 1;
                end else if ((line_idle && pending)) begin
                    line_go <= 1'b1;
                    line_tag <= ptag;
                    line_a <= pa;
                    line_b <= pb;
                    pending <= 1'b0;
                    arb <= 1;
                end
            end else if ((arb == 1)) begin
                arb <= 2;
            end else if (line_idle) begin
                arb <= 0;
            end
        end
    end
    // -------------------------------------------------------
    // Module-level statements
    // -------------------------------------------------------
    always @(*) begin
        va = pick((((state == 1021) || (state == 1040)) || (state == 1180)), index, pick(((((state == 1150) || (state == 1152)) || (state == 1154)) || (state == 1157)), ((hidden + kvcount) + jj), pick((state == 1161), (((hidden + __mul_noop(jj, kv)) + __mul_noop((head / group), head_dim)) + dd), 0)));
        ga = pick((state == 1040), pick((norm_pass == 0), (__mul_noop(2, hidden) + index), index), pick((state == 1074), col, pick((state == 1095), ((hidden + __mul_noop(head, head_dim)) + pair), pick((state == 1096), (((hidden + __mul_noop(head, head_dim)) + pair) + pairs), pick(((state == 1110) || (state == 1180)), (hidden + index), pick((state == 1141), ((hidden + __mul_noop(head, head_dim)) + col), 0))))));
        ua = pick(((state == 1021) || (state == 1040)), (kvcount + index), pick((state == 1120), ((__mul_noop(pos, kv) + __mul_noop(head, head_dim)) + pair), pick((state == 1121), (((__mul_noop(pos, kv) + __mul_noop(head, head_dim)) + pair) + pairs), pick((state == 1135), (__mul_noop(pos, kv) + index), pick((state == 1141), ((__mul_noop(jj, kv) + __mul_noop((head / group), head_dim)) + col), 0)))));
        group = (heads / kv_heads);
        s_idle = !sbuf;
    end

    // -------------------------------------------------------
    // NOT LOWERED BY THIS BACKEND
    //
    // `gen-verilog` emits synthesizable RTL. A test, an invariant and a
    // bench are simulation constructs -- yosys turns each `$display` into a
    // `$print` cell and nextpnr has no BEL to place one. They are carried by
    // `gen-verilog-for-simulation`, which lowers every declaration below.
    //
    // test      exp_zero
    // test      exp_unit
    // test      exp_deep
    // test      exp_one
    // -------------------------------------------------------

endmodule

`default_nettype wire
