#!/usr/bin/env python3
"""Decoder cost of every density-optimal layout of an 18- and a 36-bit block-RAM word.

A w-bit word holds at most n*(w) = floor(w / log2 3) trits. A layout splits the word
into groups of b bits, each a base-3 number of n*(b) trits (digit = trit + 1), placed
from bit 0 upward, larger groups first. This tool lists every multiset of group sizes
that reaches n*(w), writes each decoder as executable t27 (one module per layout, the
same digit arithmetic as t27/rtl/bram_trit_codec.t27: lanes of two bits, 00 = 0,
01 = +1, 10 = -1, and the count of invalid groups in bits 55:48), checks the generated
C against a Python statement of the rule on random words, and synthesizes each decoder
alone with yosys twice: with the flow's LUT-only mapping (-nowidelut) and with the
MUXF7/MUXF8 wide multiplexers allowed. It reports LUTs and LUT levels (ltp length
minus the input and output buffers) as JSON and a Markdown table.

  python3 tools/bram-layout-study.py --output-dir reports/fpga/layout-study-<date>-<commit>
"""
from __future__ import annotations

import argparse
import ctypes
import json
import math
import os
import random
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOG2_3 = math.log2(3)
FLOW = "synth_xilinx -flatten -abc9 -nocarry -nodsp -nowidelut -nosrl -family xc7"
WIDE = "synth_xilinx -flatten -abc9 -nocarry -nodsp -nosrl -family xc7"


def nstar(bits: int) -> int:
    n = int(bits / LOG2_3)
    while 3 ** (n + 1) <= 2 ** bits:
        n += 1
    while 3 ** n > 2 ** bits:
        n -= 1
    return n


def layouts(width: int) -> list[tuple[int, ...]]:
    """Every multiset of group sizes (bits) that fills the word and holds n*(width) trits."""
    sizes = [b for b in range(2, 17) if nstar(b) > nstar(b - 1)]
    found = set()

    def walk(rest: int, low: int, acc: list[int]) -> None:
        if rest == 0:
            if sum(nstar(b) for b in acc) == nstar(width):
                found.add(tuple(sorted(acc, reverse=True)))
            return
        for b in sizes:
            if low <= b <= rest:
                walk(rest - b, b, acc + [b])

    walk(width, 0, [])
    return sorted(found, key=lambda c: (max(c), len(c), c))


def name_of(layout: tuple[int, ...]) -> str:
    return "g" + "_".join(str(b) for b in layout)


def t27_source(layout: tuple[int, ...]) -> str:
    module = "TrinityBramLayout" + "".join(f"B{b}" for b in layout) + "T27"
    lines = [f"module {module};", "",
             f"// Decoder of the layout {layout}: groups of these many bits from bit 0 up, each a",
             "// base-3 number of n*(bits) trits. Generated by tools/bram-layout-study.py.",
             "fn lane_of_digit(digit: u16) -> u64 {",
             "    if (digit == 0) { return 2; }",
             "    if (digit == 1) { return 0; }",
             "    return 1;",
             "}", ""]
    for b in sorted(set(layout)):
        m = nstar(b)
        terms = " | ".join(("lane_of_digit(code % 3)" if k == 0 else f"(lane_of_digit((code / {3 ** k}) % 3) << {2 * k})")
                           for k in range(m))
        lines += [f"fn group{b}(code: u16) -> u64 {{",
                  f"    if (code < {3 ** m}) {{ return {terms}; }}",
                  "    return 0;", "}", "",
                  f"fn bad{b}(code: u16) -> u64 {{",
                  f"    if (code < {3 ** m}) {{ return 0; }}",
                  "    return 1;", "}", ""]
    lane_terms, bad_terms, bit, lane = [], [], 0, 0
    for b in layout:
        field = f"((word >> {bit}) & {2 ** b - 1}) as u16"
        lane_terms.append(f"(group{b}({field}) << {2 * lane})")
        bad_terms.append(f"bad{b}({field})")
        bit += b
        lane += nstar(b)
    lines += ["fn decode(word: u64) -> u64 {",
              "    var lanes: u64 = " + "\n        | ".join(lane_terms) + ";",
              "    var bad: u64 = " + " + ".join(bad_terms) + ";",
              "    return lanes | (bad << 48);", "}", "",
              "fn on_comb(x: u64) -> u64 {", "    return decode(x);", "}", "",
              "endmodule", ""]
    return "\n".join(lines), module


def py_decode(layout: tuple[int, ...], word: int) -> int:
    lanes, bad, bit, lane = 0, 0, 0, 0
    for b in layout:
        m = nstar(b)
        code = (word >> bit) & (2 ** b - 1)
        if code < 3 ** m:
            for k in range(m):
                digit = (code // 3 ** k) % 3
                lanes |= {0: 2, 1: 0, 2: 1}[digit] << (2 * (lane + k))
        else:
            bad += 1
        bit += b
        lane += m
    return lanes | (bad << 48)


def check_c(t27c: str, source: Path, layout: tuple[int, ...], work: Path, rng: random.Random) -> int:
    generated = subprocess.run([t27c, "gen-c", str(source)], capture_output=True, text=True, check=True).stdout
    c_file = work / (source.stem + ".c")
    c_file.write_text(generated, encoding="ascii")
    lib = work / ("lib" + source.stem + ".so")
    subprocess.run(["cc", "-shared", "-fPIC", "-O1", "-Wno-parentheses-equality", str(c_file), "-o", str(lib)],
                   check=True, capture_output=True)
    dll = ctypes.CDLL(str(lib))
    dll.decode.argtypes, dll.decode.restype = (ctypes.c_uint64,), ctypes.c_uint64
    width = sum(layout)
    words = [rng.getrandbits(width) for _ in range(3000)] + [0, 2 ** width - 1]
    return sum(1 for w in words if dll.decode(w) != py_decode(layout, w))


def synth(verilog: Path, module: str, script: str, work: Path) -> dict:
    ltp, stat = work / (module + ".ltp"), work / (module + ".stat")
    subprocess.run(["yosys", "-q", "-p", f"read_verilog {verilog}; {script} -top {module}; "
                    f"tee -q -o {ltp} ltp -noff; tee -q -o {stat} stat"], check=True, capture_output=True)
    length = int(re.search(r"length=(\d+)", ltp.read_text()).group(1))
    cells = {m.group(2): int(m.group(1)) for m in re.finditer(r"^\s+(\d+)\s+(\S+)$", stat.read_text(), re.M)}
    luts = sum(n for c, n in cells.items() if re.fullmatch(r"LUT[1-6]", c))
    return {"luts": luts, "muxf7": cells.get("MUXF7", 0), "muxf8": cells.get("MUXF8", 0), "levels": length - 2}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--widths", default="18,36")
    args = parser.parse_args()
    t27c = str(Path(os.environ["T27_ROOT"]) / "target/release/t27c")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(2026)
    rows = []
    with tempfile.TemporaryDirectory(prefix="bram-layouts-") as tmp:
        work = Path(tmp)
        for width in (int(w) for w in args.widths.split(",")):
            for layout in layouts(width):
                text, module = t27_source(layout)
                source = args.output_dir / f"w{width}_{name_of(layout)}.t27"
                source.write_text(text, encoding="utf-8")
                verilog = work / (module + ".v")
                verilog.write_text(subprocess.run([t27c, "gen-verilog", str(source)], capture_output=True,
                                                  text=True, check=True).stdout, encoding="utf-8")
                mismatches = check_c(t27c, source, layout, work, rng)
                row = {"width": width, "layout": list(layout), "trits": [nstar(b) for b in layout],
                       "module": module, "c_mismatches": mismatches,
                       "lut_only": synth(verilog, module, FLOW, work), "wide_mux": synth(verilog, module, WIDE, work)}
                rows.append(row)
                print(f"w{width} {layout}: {row['lut_only']['luts']} LUT / {row['lut_only']['levels']} levels; "
                      f"with MUXF7/8 {row['wide_mux']['luts']} LUT + {row['wide_mux']['muxf7'] + row['wide_mux']['muxf8']} MUXF / "
                      f"{row['wide_mux']['levels']} levels; C mismatches {mismatches}", flush=True)
    report = {"schema": "trinity.bram-layout-study.v1", "yosys_lut_only": FLOW, "yosys_wide_mux": WIDE,
              "levels": "ltp -noff length minus the input and output buffers", "rows": rows}
    (args.output_dir / "layout_study.json").write_text(json.dumps(report, indent=1) + "\n", encoding="utf-8")
    table = ["| Width | Groups (bits) | Trits per group | LUT (LUT-only) | Levels | LUT + MUXF (wide) | Levels |",
             "| ---: | --- | --- | ---: | ---: | ---: | ---: |"]
    for r in sorted(rows, key=lambda r: (r["width"], r["lut_only"]["luts"])):
        w = r["wide_mux"]
        table.append(f"| {r['width']} | {', '.join(map(str, r['layout']))} | {', '.join(map(str, r['trits']))} | "
                     f"{r['lut_only']['luts']} | {r['lut_only']['levels']} | {w['luts']} + {w['muxf7'] + w['muxf8']} | {w['levels']} |")
    (args.output_dir / "layout_study.md").write_text("\n".join(table) + "\n", encoding="utf-8")
    if any(r["c_mismatches"] for r in rows):
        sys.exit("a generated decoder disagrees with the Python rule")


if __name__ == "__main__":
    main()
