#!/usr/bin/env python3
"""Generate t27/runtimes.t27 from specs/runtimes/*.json (issue #51).

Each spec pins one runtime (repository, commit, blob SHA of every cited file)
and lists the ggml type ids it defines with their block size, block bytes and
byte-count rule, the architecture names its model mapping turns into a model
class, and those among them it refuses as a main model. The t27
module restates them as functions, so every verdict that depends on a runtime
reads the same table. `--check` compares the committed module with a fresh
generation and fails on any difference.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
SPECS = ROOT / "specs" / "runtimes"
OUT = ROOT / "t27" / "runtimes.t27"
ORDER = ("llama_cpp", "prismml", "bitnet_cpp")
RULES = {"blocks": "TRT_RULE_BLOCKS", "i2s": "TRT_RULE_I2S", "tl2": "TRT_RULE_TL2"}


def load() -> list[dict]:
    specs = []
    for name in ORDER:
        spec = json.loads((SPECS / f"{name}.json").read_text())
        if spec.get("schema") != "trinity.runtime-tables.v1":
            raise SystemExit(f"{name}: unexpected schema {spec.get('schema')}")
        ids = [t["id"] for t in spec["types"]]
        if ids != sorted(set(ids)) or any(t["id"] >= spec["type_count"] for t in spec["types"]):
            raise SystemExit(f"{name}: type ids must be unique, sorted and below type_count")
        if any(t["rule"] not in RULES or t["blck"] < 1 or t["bytes"] < 1 for t in spec["types"]):
            raise SystemExit(f"{name}: every type needs a known rule and positive sizes")
        if len(set(spec["archs"])) != len(spec["archs"]) or any(not a or "\"" in a or "\\" in a for a in spec["archs"]):
            raise SystemExit(f"{name}: architecture names must be unique plain strings")
        if not set(spec.get("archs_refused_as_main", [])) <= set(spec["archs"]):
            raise SystemExit(f"{name}: archs_refused_as_main must name mapped architectures")
        specs.append(spec)
    return specs


def generate(specs: list[dict]) -> str:
    out = ["// SPDX-License-Identifier: Apache-2.0",
           "// GENERATED by tools/generate-runtime-tables.py from specs/runtimes/*.json; do not edit.",
           "// Runtime tables (issue #51): for each pinned runtime, the ggml type ids it defines",
           "// (block size in weights, bytes per block, the ggml_nbytes rule), the architecture",
           "// names its model mapping turns into a model class and those it refuses as a main",
           "// model. Sources, per runtime:"]
    for spec in specs:
        out.append(f"//   {spec['id']} {spec['runtime']}: {spec['repo']}@{spec['commit']}")
    out += ["// Their files and blob SHAs are listed in the specs; the rules they restate are cited",
            "// in t27/live.t27, the module that reads these tables.",
            "module TrinityMemoryRuntimes {"]
    for spec in specs:
        const = "TRT_" + spec["runtime"].split()[0].upper().replace(".", "_").replace("-", "_")
        out.append(f"    const {const}: i32 = {spec['id']};")
    out += ["    const TRT_RULE_BLOCKS: i32 = 0;  // ne0 / block * bytes, times the other dims",
            "    const TRT_RULE_I2S: i32 = 1;     // bitnet.cpp I2_S and TL1: elements / 4 + 32",
            "    const TRT_RULE_TL2: i32 = 2;     // bitnet.cpp TL2, ggml_nbytes special case",
            "",
            "    // GGML_TYPE_COUNT: ids at or above it are refused by gguf.cpp.",
            "    fn trt_type_count(runtime: i32) -> u32 {"]
    for spec in specs:
        out.append(f"        if (runtime == {spec['id']}) {{ return {spec['type_count']}; }}")
    out += ["        return 0;", "    }", ""]
    for field, doc in (("blck", "Weights per block; 0 when the runtime defines no traits for the id."),
                       ("bytes", "Bytes per block; 0 when the runtime defines no traits for the id.")):
        out.append(f"    // {doc}")
        out.append(f"    fn trt_{field}(runtime: i32, type_id: u32) -> u64 {{")
        for spec in specs:
            out.append(f"        if (runtime == {spec['id']}) {{")
            for t in spec["types"]:
                out.append(f"            if (type_id == {t['id']}) {{ return {t[field]}; }}  // {t['name']}")
            out.append("            return 0;")
            out.append("        }")
        out += ["        return 0;", "    }", ""]
    out.append("    // The ggml_nbytes rule of the id (TRT_RULE_*).")
    out.append("    fn trt_rule(runtime: i32, type_id: u32) -> i32 {")
    for spec in specs:
        special = [t for t in spec["types"] if t["rule"] != "blocks"]
        if not special:
            continue
        out.append(f"        if (runtime == {spec['id']}) {{")
        for t in special:
            out.append(f"            if (type_id == {t['id']}) {{ return {RULES[t['rule']]}; }}  // {t['name']}")
        out.append("        }")
    out += ["        return TRT_RULE_BLOCKS;", "    }", ""]
    out.append("    // Whether the runtime's model loader applies prism.hadamard.* (only the PrismML fork).")
    out.append("    fn trt_hadamard(runtime: i32) -> bool {")
    for spec in specs:
        out.append(f"        if (runtime == {spec['id']}) {{ return {'true' if spec['hadamard'] else 'false'}; }}")
    out += ["        return false;", "    }", ""]
    for field, doc in (("archs", ("Whether data[at .. at + size) is an architecture name the runtime's model mapping",
                                   "turns into a model class (the caller passes the name up to its first NUL, as the",
                                   "loader reads it); other names are refused before the hyperparameters.")),
                       ("archs_refused_as_main", ("Whether the architecture is mapped but refused as a main model after the",
                                                  "hyperparameters (clip in llama.cpp and the PrismML fork)."))):
        function = "trt_arch_known" if field == "archs" else "trt_arch_refused_as_main"
        out += [f"    // {line}" for line in doc]
        out.append(f"    fn {function}(runtime: i32, data: []u8, at: usize, size: usize) -> bool {{")
        for spec in specs:
            names = spec.get(field, [])
            if not names:
                continue
            out.append(f"        if (runtime == {spec['id']}) {{")
            for arch in names:
                out.append(f"            if (tf_same_text(data, at, size, \"{arch}\", {len(arch.encode())})) {{ return true; }}")
            out.append("            return false;")
            out.append("        }")
        out += ["        return false;", "    }", ""]
    out[-1:] = ["}", ""]
    return "\n".join(out)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when t27/runtimes.t27 differs from a fresh generation")
    args = parser.parse_args(argv)
    text = generate(load())
    if args.check:
        if OUT.read_text() != text:
            print(f"{OUT} is stale: run python3 tools/generate-runtime-tables.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
