#!/usr/bin/env python3
"""Generate the on-device trace player bank for the AX7203 measurement track (#10).

Reads the cycle-exact `dot_trace` and `storage_trace` vectors of
`conformance/memory_stream_compute.json` and writes

  build/fpga/tms_trace_bank.v        ROMs (stimulus/expected words packed exactly as
                                     tests/tb_spec_dot_trace.v and tests/tb_spec_storage_trace.v
                                     read them), one DUT instance per distinct parameter set,
                                     and the vector table used by fpga/ax7203/tms_trace_player.v
  build/fpga/tms_trace_manifest.json vector order, packed words, counter semantics and the
                                     source hash, consumed by tools/fpga-capture.py

The packing functions are imported from tests/spec_stream_replay.py so the FPGA
player and the Icarus replay cannot drift apart.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tests"))
import spec_stream_replay as replay  # noqa: E402

SOURCE = ROOT / "conformance" / "memory_stream_compute.json"
MAX_VECTORS = 1023
MAX_CYCLES = 1023

# Counter semantics (index -> meaning), evaluated by the player at every stepped cycle
# from the stimulus word of that cycle and the outputs the core sees at the consuming
# edge (stimulus applied, state not yet advanced), i.e. the handshake values.
DOT_COUNTERS = [
    "beats accepted: in_valid && in_ready at the consuming edge",
    "results delivered: out_valid && out_ready at the consuming edge",
    "input stalls: in_valid && !in_ready at the consuming edge",
    "output holds: out_valid && !out_ready at the consuming edge",
    "error results delivered: out_valid && out_ready && out_error at the consuming edge",
    "reset cycles: reset asserted",
]
STORAGE_COUNTERS = [
    "loads accepted: load_en && load_ready at the consuming edge",
    "words delivered: out_valid after the edge",
    "lanes delivered: popcount(out_lane_mask) when out_valid after the edge",
    "invalid words delivered: out_valid && !out_code_valid after the edge",
    "starts accepted: start && !busy && !rst at the consuming edge",
    "reset cycles: rst asserted",
]


def load_vectors(document):
    vectors, duts = [], []
    for vector in document["vectors"]:
        if vector["kind"] == "dot_trace":
            stimulus = [replay.dot_stimulus_word(step) for step in vector["cycles"]]
            expected = [replay.dot_expected_word(step) for step in vector["cycles"]]
            key = ("dot", bool(vector["dense"]), int(vector["acc_width"]))
            params = {"dense": bool(vector["dense"]), "acc_width": int(vector["acc_width"])}
        elif vector["kind"] == "storage_trace":
            stimulus = [replay.storage_stimulus_word(step) for step in vector["cycles"]]
            expected = [replay.storage_expected_word(step) for step in vector["cycles"]]
            key = ("storage", bool(vector["dense"]), int(vector["trit_count"]))
            params = {"dense": bool(vector["dense"]), "trit_count": int(vector["trit_count"])}
        else:
            continue
        if key not in duts:
            duts.append(key)
        if len(stimulus) != vector["cycle_count"] or not stimulus:
            raise SystemExit(f"{vector['id']}: cycle_count disagrees with the cycles list")
        if any(word >> 64 for word in stimulus) or any(word >> 36 for word in expected):
            raise SystemExit(f"{vector['id']}: packed word does not fit")
        vectors.append({
            "id": vector["id"], "kind": key[0], "dut": duts.index(key), "params": params,
            "cycles": len(stimulus), "stimulus": stimulus, "expected": expected,
        })
    if len(vectors) > MAX_VECTORS or sum(v["cycles"] for v in vectors) > MAX_CYCLES:
        raise SystemExit("too many vectors or cycles for the 10-bit player counters")
    return vectors, duts


def emit_bank(vectors, duts, source_hash):
    total = sum(v["cycles"] for v in vectors)
    lines = [
        "// DO NOT EDIT - generated by tools/generate-fpga-trace-player.py from",
        f"// conformance/memory_stream_compute.json (sha256 {source_hash}).",
        "// ROM words use the packing of tests/tb_spec_dot_trace.v and tests/tb_spec_storage_trace.v.",
        "`timescale 1ns/1ps",
        "`default_nettype none",
        "module tms_trace_bank (",
        "    input  wire        clk,",
        "    input  wire        dut_rst_n,",
        "    input  wire        step,",
        "    input  wire [9:0]  vector,",
        "    input  wire [9:0]  addr,",
        "    input  wire [63:0] stim_q,",
        "    output wire [63:0] stimulus,",
        "    output wire [35:0] expected,",
        "    output wire [9:0]  vector_base,",
        "    output wire [9:0]  vector_cycles,",
        "    output wire        vector_kind,",
        "    output wire [3:0]  vector_dut,",
        "    output wire [9:0]  vector_count,",
        "    output wire [9:0]  cycle_count,",
        "    output wire [35:0] observed",
        ");",
        f"    assign vector_count = 10'd{len(vectors)};",
        f"    assign cycle_count = 10'd{total};",
        "    // Lookups are functions used in continuous assignments so that simulation",
        "    // evaluates them at time zero as well; they synthesize to plain ROM logic.",
        "    function [63:0] f_stimulus;",
        "        input [9:0] a;",
        "        case (a)",
    ]
    flat = 0
    for vector in vectors:
        for stim in vector["stimulus"]:
            lines.append(f"            10'd{flat}: f_stimulus = 64'h{stim:016x};")
            flat += 1
    lines += [
        "            default: f_stimulus = 64'd0;",
        "        endcase",
        "    endfunction",
        "    function [35:0] f_expected;",
        "        input [9:0] a;",
        "        case (a)",
    ]
    flat = 0
    for vector in vectors:
        for exp in vector["expected"]:
            lines.append(f"            10'd{flat}: f_expected = 36'h{exp:09x};")
            flat += 1
    lines += [
        "            default: f_expected = 36'd0;",
        "        endcase",
        "    endfunction",
        "    function [24:0] f_vector;  // {dut[3:0], kind, base[9:0], cycles[9:0]}",
        "        input [9:0] v;",
        "        case (v)",
    ]
    base = 0
    for index, vector in enumerate(vectors):
        kind = 1 if vector["kind"] == "storage" else 0
        lines.append(f"            10'd{index}: f_vector = {{4'd{vector['dut']}, 1'b{kind}, 10'd{base}, 10'd{vector['cycles']}}}; // {vector['id']}")
        base += vector["cycles"]
    lines += [
        "            default: f_vector = 25'd0;",
        "        endcase",
        "    endfunction",
        "    assign stimulus = f_stimulus(addr);",
        "    assign expected = f_expected(addr);",
        "    wire [24:0] entry = f_vector(vector);",
        "    assign vector_dut = entry[24:21];",
        "    assign vector_kind = entry[20];",
        "    assign vector_base = entry[19:10];",
        "    assign vector_cycles = entry[9:0];",
    ]
    for index, (kind, dense, size) in enumerate(duts):
        lines.append(f"    wire [35:0] obs_{index};")
        if kind == "dot":
            lines.append(f"    tms_dot_dut #(.DENSE5({1 if dense else 0}), .ACC_WIDTH({size})) dut_{index} (")
        else:
            lines.append(f"    tms_storage_dut #(.DENSE5({1 if dense else 0}), .TRIT_COUNT({size})) dut_{index} (")
        lines.append(f"        .clk(clk), .rst_n(dut_rst_n), .en(step && (vector_dut == 4'd{index})),")
        lines.append(f"        .stim(stim_q), .observed(obs_{index}));")
    mux = " : ".join(f"(vector_dut == 4'd{i}) ? obs_{i}" for i in range(len(duts)))
    lines.append(f"    assign observed = {mux} : 36'd0;")
    lines += ["endmodule", "`default_nettype wire", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", default=str(SOURCE))
    parser.add_argument("--output-dir", default=str(ROOT / "build" / "fpga"))
    parser.add_argument("--check", action="store_true", help="fail if the outputs would change")
    args = parser.parse_args()
    source = Path(args.source)
    raw = source.read_bytes()
    source_hash = hashlib.sha256(raw).hexdigest()
    vectors, duts = load_vectors(json.loads(raw))
    bank = emit_bank(vectors, duts, source_hash)
    manifest = {
        "schema": "trinity.fpga-trace-manifest.v1",
        "source": {"path": str(source.relative_to(ROOT)) if source.is_relative_to(ROOT) else str(source),
                   "sha256": source_hash},
        "line_format": "tag(1) + a(8 hex) + b(9 hex) + LF; tags H V C E K F D",
        "duts": [{"index": i, "kind": k, "dense": d, ("acc_width" if k == "dot" else "trit_count"): s}
                 for i, (k, d, s) in enumerate(duts)],
        "vectors": [{
            "index": i, "id": v["id"], "kind": v["kind"], "dut": v["dut"], **v["params"],
            "cycles": v["cycles"],
            "stimulus": [f"{w:016x}" for w in v["stimulus"]],
            "expected": [f"{w:09x}" for w in v["expected"]],
        } for i, v in enumerate(vectors)],
        "counters": {"dot": DOT_COUNTERS, "storage": STORAGE_COUNTERS},
        "total_cycles": sum(v["cycles"] for v in vectors),
    }
    text = json.dumps(manifest, indent=1, sort_keys=True) + "\n"
    out = Path(args.output_dir)
    targets = {out / "tms_trace_bank.v": bank, out / "tms_trace_manifest.json": text}
    if args.check:
        stale = [str(p) for p, body in targets.items() if not p.is_file() or p.read_text(encoding="utf-8") != body]
        if stale:
            raise SystemExit("stale generated player files: " + ", ".join(stale))
        print("fpga trace player outputs are current")
        return
    out.mkdir(parents=True, exist_ok=True)
    for path, body in targets.items():
        path.write_text(body, encoding="utf-8")
    print(f"wrote {len(vectors)} vectors, {manifest['total_cycles']} cycles, {len(duts)} DUT instances -> {out}")


if __name__ == "__main__":
    main()
