## ALINX AX7203 (XC7A200T-FBG484-2) DDR3 build, issue #60: pins shared by the
## x16 and x32 variants. The Makefile appends tms_ddr3_x32.xdc (byte lanes 2-3)
## for DDR3_WIDTH=32 and a generated clock file (create_clock on the four PLL
## outputs, which nextpnr-xilinx 45a986b8 does not derive from the input clock;
## 0.9.x derives them, openXC7/nextpnr-xilinx#155).
## DDR3 pin assignments as on the board: litex-hub/litex-boards 9f84c87
## litex_boards/platforms/alinx_ax7203.py L102-L125, which agree pin for pin
## with a third-party AX7203 MIG project and the ALINX manual excerpts (research
## notes of #60). DQ, DQS and DM are in bank 35 (byte lane n in byte group Tn),
## address, command and CK in bank 34; VCCO of both banks is 1.5 V. HR banks have
## no DCI, so DQ and DQS use the on-chip split termination for reads. nextpnr
## ignores INTERNAL_VREF (xdc.cc) and writes VREF.V_675_MV for every bank with a
## single-ended SSTL input: bank 35 here, see docs/hardware.md.
## Clock, reset, LEDs and UART as in ../tms_trace_player.xdc (verified on this board).
## nextpnr-xilinx does not expand grouped assignments: one port per line.

# 200 MHz oscillator, reset key, LEDs, UART transmit
set_property PACKAGE_PIN R4 [get_ports clk200_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports clk200_p]
set_property PACKAGE_PIN T4 [get_ports clk200_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports clk200_n]
set_property PACKAGE_PIN T6 [get_ports rst_n]
set_property IOSTANDARD LVCMOS15 [get_ports rst_n]
set_property PACKAGE_PIN B13 [get_ports led[0]]
set_property IOSTANDARD LVCMOS18 [get_ports led[0]]
set_property PACKAGE_PIN C13 [get_ports led[1]]
set_property IOSTANDARD LVCMOS18 [get_ports led[1]]
set_property PACKAGE_PIN D14 [get_ports led[2]]
set_property IOSTANDARD LVCMOS18 [get_ports led[2]]
set_property PACKAGE_PIN D15 [get_ports led[3]]
set_property IOSTANDARD LVCMOS18 [get_ports led[3]]
set_property PACKAGE_PIN N15 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
create_clock -period 5.000 -name clk200 [get_ports clk200_p]

# address, bank, command, CK, CKE, ODT, CS#, RESET#: bank 34, shared by both chips
set_property PACKAGE_PIN AA4 [get_ports ddr3_addr[0]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[0]]
set_property SLEW FAST [get_ports ddr3_addr[0]]
set_property PACKAGE_PIN AB2 [get_ports ddr3_addr[1]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[1]]
set_property SLEW FAST [get_ports ddr3_addr[1]]
set_property PACKAGE_PIN AA5 [get_ports ddr3_addr[2]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[2]]
set_property SLEW FAST [get_ports ddr3_addr[2]]
set_property PACKAGE_PIN AB5 [get_ports ddr3_addr[3]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[3]]
set_property SLEW FAST [get_ports ddr3_addr[3]]
set_property PACKAGE_PIN AB1 [get_ports ddr3_addr[4]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[4]]
set_property SLEW FAST [get_ports ddr3_addr[4]]
set_property PACKAGE_PIN U3 [get_ports ddr3_addr[5]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[5]]
set_property SLEW FAST [get_ports ddr3_addr[5]]
set_property PACKAGE_PIN W1 [get_ports ddr3_addr[6]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[6]]
set_property SLEW FAST [get_ports ddr3_addr[6]]
set_property PACKAGE_PIN T1 [get_ports ddr3_addr[7]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[7]]
set_property SLEW FAST [get_ports ddr3_addr[7]]
set_property PACKAGE_PIN V2 [get_ports ddr3_addr[8]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[8]]
set_property SLEW FAST [get_ports ddr3_addr[8]]
set_property PACKAGE_PIN U2 [get_ports ddr3_addr[9]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[9]]
set_property SLEW FAST [get_ports ddr3_addr[9]]
set_property PACKAGE_PIN Y1 [get_ports ddr3_addr[10]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[10]]
set_property SLEW FAST [get_ports ddr3_addr[10]]
set_property PACKAGE_PIN W2 [get_ports ddr3_addr[11]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[11]]
set_property SLEW FAST [get_ports ddr3_addr[11]]
set_property PACKAGE_PIN Y2 [get_ports ddr3_addr[12]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[12]]
set_property SLEW FAST [get_ports ddr3_addr[12]]
set_property PACKAGE_PIN U1 [get_ports ddr3_addr[13]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[13]]
set_property SLEW FAST [get_ports ddr3_addr[13]]
set_property PACKAGE_PIN V3 [get_ports ddr3_addr[14]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_addr[14]]
set_property SLEW FAST [get_ports ddr3_addr[14]]
set_property PACKAGE_PIN AA3 [get_ports ddr3_ba[0]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_ba[0]]
set_property SLEW FAST [get_ports ddr3_ba[0]]
set_property PACKAGE_PIN Y3 [get_ports ddr3_ba[1]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_ba[1]]
set_property SLEW FAST [get_ports ddr3_ba[1]]
set_property PACKAGE_PIN Y4 [get_ports ddr3_ba[2]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_ba[2]]
set_property SLEW FAST [get_ports ddr3_ba[2]]
set_property PACKAGE_PIN V4 [get_ports ddr3_ras_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_ras_n]
set_property SLEW FAST [get_ports ddr3_ras_n]
set_property PACKAGE_PIN W4 [get_ports ddr3_cas_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cas_n]
set_property SLEW FAST [get_ports ddr3_cas_n]
set_property PACKAGE_PIN AA1 [get_ports ddr3_we_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_we_n]
set_property SLEW FAST [get_ports ddr3_we_n]
set_property PACKAGE_PIN T5 [get_ports ddr3_cke]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cke]
set_property SLEW FAST [get_ports ddr3_cke]
set_property PACKAGE_PIN U5 [get_ports ddr3_odt]
set_property IOSTANDARD SSTL15 [get_ports ddr3_odt]
set_property SLEW FAST [get_ports ddr3_odt]
set_property PACKAGE_PIN AB3 [get_ports ddr3_cs_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cs_n]
set_property SLEW FAST [get_ports ddr3_cs_n]
set_property PACKAGE_PIN W6 [get_ports ddr3_reset_n]
set_property IOSTANDARD LVCMOS15 [get_ports ddr3_reset_n]
set_property SLEW FAST [get_ports ddr3_reset_n]
set_property PACKAGE_PIN R3 [get_ports ddr3_ck_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_ck_p]
set_property SLEW FAST [get_ports ddr3_ck_p]
set_property PACKAGE_PIN R2 [get_ports ddr3_ck_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_ck_n]
set_property SLEW FAST [get_ports ddr3_ck_n]

# byte lane 0 (chip U6), bank 35, byte group T0
set_property PACKAGE_PIN C2 [get_ports ddr3_dq[0]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[0]]
set_property SLEW FAST [get_ports ddr3_dq[0]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[0]]
set_property PACKAGE_PIN G1 [get_ports ddr3_dq[1]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[1]]
set_property SLEW FAST [get_ports ddr3_dq[1]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[1]]
set_property PACKAGE_PIN A1 [get_ports ddr3_dq[2]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[2]]
set_property SLEW FAST [get_ports ddr3_dq[2]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[2]]
set_property PACKAGE_PIN F3 [get_ports ddr3_dq[3]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[3]]
set_property SLEW FAST [get_ports ddr3_dq[3]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[3]]
set_property PACKAGE_PIN B2 [get_ports ddr3_dq[4]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[4]]
set_property SLEW FAST [get_ports ddr3_dq[4]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[4]]
set_property PACKAGE_PIN F1 [get_ports ddr3_dq[5]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[5]]
set_property SLEW FAST [get_ports ddr3_dq[5]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[5]]
set_property PACKAGE_PIN B1 [get_ports ddr3_dq[6]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[6]]
set_property SLEW FAST [get_ports ddr3_dq[6]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[6]]
set_property PACKAGE_PIN E2 [get_ports ddr3_dq[7]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[7]]
set_property SLEW FAST [get_ports ddr3_dq[7]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[7]]
set_property PACKAGE_PIN E1 [get_ports ddr3_dqs_p[0]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_dqs_p[0]]
set_property SLEW FAST [get_ports ddr3_dqs_p[0]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dqs_p[0]]
set_property PACKAGE_PIN D1 [get_ports ddr3_dqs_n[0]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_dqs_n[0]]
set_property SLEW FAST [get_ports ddr3_dqs_n[0]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dqs_n[0]]
set_property PACKAGE_PIN D2 [get_ports ddr3_dm[0]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dm[0]]
set_property SLEW FAST [get_ports ddr3_dm[0]]
# byte lane 1 (chip U6), bank 35, byte group T1
set_property PACKAGE_PIN H3 [get_ports ddr3_dq[8]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[8]]
set_property SLEW FAST [get_ports ddr3_dq[8]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[8]]
set_property PACKAGE_PIN G3 [get_ports ddr3_dq[9]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[9]]
set_property SLEW FAST [get_ports ddr3_dq[9]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[9]]
set_property PACKAGE_PIN H2 [get_ports ddr3_dq[10]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[10]]
set_property SLEW FAST [get_ports ddr3_dq[10]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[10]]
set_property PACKAGE_PIN H5 [get_ports ddr3_dq[11]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[11]]
set_property SLEW FAST [get_ports ddr3_dq[11]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[11]]
set_property PACKAGE_PIN J1 [get_ports ddr3_dq[12]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[12]]
set_property SLEW FAST [get_ports ddr3_dq[12]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[12]]
set_property PACKAGE_PIN J5 [get_ports ddr3_dq[13]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[13]]
set_property SLEW FAST [get_ports ddr3_dq[13]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[13]]
set_property PACKAGE_PIN K1 [get_ports ddr3_dq[14]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[14]]
set_property SLEW FAST [get_ports ddr3_dq[14]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[14]]
set_property PACKAGE_PIN H4 [get_ports ddr3_dq[15]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dq[15]]
set_property SLEW FAST [get_ports ddr3_dq[15]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dq[15]]
set_property PACKAGE_PIN K2 [get_ports ddr3_dqs_p[1]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_dqs_p[1]]
set_property SLEW FAST [get_ports ddr3_dqs_p[1]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dqs_p[1]]
set_property PACKAGE_PIN J2 [get_ports ddr3_dqs_n[1]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_dqs_n[1]]
set_property SLEW FAST [get_ports ddr3_dqs_n[1]]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports ddr3_dqs_n[1]]
set_property PACKAGE_PIN G2 [get_ports ddr3_dm[1]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_dm[1]]
set_property SLEW FAST [get_ports ddr3_dm[1]]
# PLL outputs (DDR3_PLL_MULT=5, DDR3_DDR_DIV=3), written by fpga/ax7203/Makefile
create_clock -period 12.000 -name clk_ctrl [get_nets clk_ctrl]
create_clock -period 3.000 -name clk_ddr [get_nets clk_ddr]
create_clock -period 5.000 -name clk_ref [get_nets clk_ref]
create_clock -period 3.000 -name clk_ddr_90 [get_nets clk_ddr_90]
