/* Driver for the gguf_verdicts evidence claim (tools/evidence/gguf_verdicts.py).
 * It is compiled against the C generated by the pinned t27c from t27/json.t27,
 * t27/formats.t27, t27/runtimes.t27 and t27/live.t27, and does no GGUF parsing
 * of its own: it decodes the hex of one header per input line ("<file size> <hex>")
 * and prints what the generated code answers, using the same calls as
 * trinity_memory/live.py check_model for a model of one file:
 *   tlv_model for every runtime, tlv_native, tlv_ternary_count, tlv_file_verdict
 *   and tlv_walk's per-record layout diagnosis in the runtime the file is for.
 * Output lines: "R <runtime> <verdict> <status> <part> <record> <expected> <found>"
 * (four per case, runtimes 1..4) then "C <native> <ternary> <file verdict> <fits PQ2_0> <records read>". */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
double tm_json_strtod(uint8_t *);
#include "json.h"
#include "formats.h"
#include "runtimes.h"
#include "live.h"

double tm_json_strtod(uint8_t *text) { return strtod((const char *)text, NULL); }

static int hex(int c) { return c <= '9' ? c - '0' : c - 'a' + 10; }

int main(void) {
    static char line[1 << 20];
    while (fgets(line, sizeof line, stdin)) {
        unsigned long long file_size = strtoull(line, NULL, 10);
        char *p = strchr(line, ' ');
        if (!p) return 2;
        p++;
        size_t n = strcspn(p, "\r\n") / 2;
        uint8_t *data = malloc(n ? n : 1);
        for (size_t i = 0; i < n; i++) data[i] = (uint8_t)(hex(p[2 * i]) * 16 + hex(p[2 * i + 1]));
        uint64_t row[5] = {0, n, file_size, 0, 0};
        int32_t native = tlv_native(data, n, row, 1);
        int32_t runtime = native ? native : 1;
        int32_t native_run = -1, native_status = 0;
        for (int32_t r = 1; r <= 4; r++) {
            TLVRun run;
            memset(&run, 0, sizeof run);
            int32_t verdict = tlv_model(data, n, row, 1, r, &run);
            printf("R %d %d %d %llu %llu %llu %llu\n", r, verdict, run.status, (unsigned long long)run.part,
                   (unsigned long long)run.record, (unsigned long long)run.expected, (unsigned long long)run.found);
            if (r == runtime) { native_run = verdict; native_status = run.status; }
        }
        uint64_t ternary = tlv_ternary_count(data, n, row, 1, runtime);
        int32_t fv = tlv_file_verdict(native_run, native_status, ternary, native);
        int32_t st[256], fit[256]; uint32_t types[256]; uint64_t at[256], sz[256];
        TLVWalk w;
        memset(&w, 0, sizeof w);
        tlv_walk(data, 0, n, file_size, runtime, st, fit, types, at, sz, 256, &w);
        uint64_t fits = 0;
        for (uint64_t i = 0; i < w.read && i < 256; i++) if (st[i] < 0 && fit[i] == TF_PQ2_0) fits++;
        printf("C %d %llu %d %llu %llu\n", native, (unsigned long long)ternary, fv, (unsigned long long)fits,
               (unsigned long long)w.read);
        free(data);
    }
    return 0;
}
